### ISSUE TITLE
Error kotlin.Result$Failure cannot be cast to Type when optimizing kotlin coroutines code

### ISSUE THREAD

**Issue by netomi** [Guardsquare/proguard#1]
As reported at other places already:

https://github.com/Kotlin/kotlinx.coroutines/issues/1035

The bug has already been identified and fixed for DexGuard (DGD-1298), the fix has to be applied to ProGuard as well.

Created this ticket to trace the fix in a proguard release.

**Comment by EricLafortune** [comment]
Fixed for the upcoming ProGuard 6.2.0.

**Comment by netomi** [comment]
ProGuard 6.2.0 has been released.

**Comment by Jekton** [comment]
By upgrade to proguard 6.2.2, it seems that some code in our AAB module failed oddly. For example, java.lang.IllegalAccessError: Method 'boolean our.package.name.f.x()' is inaccessible to class 'our.package.name.u'
