### ISSUE TITLE
is there a way to specify unique class short name?

### ISSUE THREAD

**Issue by dong8chao3** [Guardsquare/proguard#101]
after obfuscated, i want every .class file have a unique name. but now the class in different package will have the same names, a.class b.class. even i specify a class name dictionary file, proGuard will only reuse the first some words.

**Comment by dzan** [comment]
Hi @dong8chao3 ,

Thanks for reaching out!

The aim of the issue tracker here is to address technical issues and bugs. For usage questions like this, please use the community instead: https://community.guardsquare.com
