### ISSUE TITLE
Stack size becomes negative after instruction putfield

### ISSUE THREAD

**Issue by davidgiga1993** [Guardsquare/proguard#108]
When applying proguard to an app which uses the huawei IAP dependency ('com.huawei.hms:iap:5.0.4.301') proguard failes with the error below.
Tested with proguard `7.0.0` and `7.0.1`.

It looks like the code inside the maven package has already been optimized using proguard, could this be the issue?
I tried to use `-dontwarn` and `-keep` for this package as well but it doesn't seem to help.

Error
```
Optimizing (pass 2/10)...
Unexpected error while computing stack sizes:
  Class       = [com/huawei/hianalytics/ab/bc/ef/bc]
  Method      = [ab(I)V]
  Exception   = [java.lang.IllegalArgumentException] (Stack size becomes negative after instruction [29] putfield #11 = Fieldref(com/huawei/hianalytics/ab/bc/ef/bc.bc I) in [com/huawei/hianalytics/ab/bc/ef/bc.ab(I)V])
Unexpected error while editing code:
  Class       = [com/huawei/hianalytics/ab/bc/ef/bc]
  Method      = [ab(I)V]
  Exception   = [java.lang.IllegalArgumentException] (Stack size becomes negative after instruction [29] putfield #11 = Fieldref(com/huawei/hianalytics/ab/bc/ef/bc.bc I) in [com/huawei/hianalytics/ab/bc/ef/bc.ab(I)V])

```

proguard file
```
-optimizations !code/simplification/cast,!field/*,!class/merging/*
-optimizationpasses 10
-allowaccessmodification
-dontpreverify
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-verbose


# Huawei IAP
-keep class com.hianalytics.android.** { *; }
-keep class com.huawei.updatesdk.** { *; }
-keep class com.huawei.hms.** { *; }
-keep class com.huawei.hianalytics.** { *; }

-dontwarn com.huawei.hms.framework.network.restclient.**
-dontwarn com.huawei.libcore.**
-dontwarn com.huawei.android.os.**
-dontwarn com.huawei.secure.android.common.**
-dontwarn com.huawei.hms.framework.**
-dontwarn com.huawei.hianalytics.**
```

**Comment by mrjameshamilton** [comment]
Hi @davidgiga1993 , thanks for the report! Do you have a full sample to reproduce the issue? 

As a workaround, you could try the `includecode` modifier on the `-keep` rule, this will prevent code optimization as well e.g.

```
-keep,includecode class com.huawei.hianalytics.ab.bc.ef.bc { *; }
```

**Comment by davidgiga1993** [comment]
Thanks for your reply. I've tried to create a sample project to reproduce the issue. Interestingly it works when using just this library in an empty project with the same proguard file. I also use the library in the same way so proguard doesn't remove the code by any chance.

The project which has this issue has more than 200k LOC so I just assume it's some sort of sideeffect?

The `includecode` flag seems to have worked around the issue, proguard now doesn't crash anymore.

**Comment by mrjameshamilton** [comment]
Indeed, it could be a combination of optimizations causing the problem and knock-on effects of other optimizations in the code base. I'll close this issue for now but if you are able to reproduce the issue in the future please re-open!
