### ISSUE TITLE
Broken pre-made gradle build configurations

### ISSUE THREAD

**Issue by fluse1367** [Guardsquare/proguard#11]
Hello,
the following lines cause issues when trying to run:
https://github.com/Guardsquare/proguard/blob/f509ce9efb39b4a1b22120e9b6a5043338c52afc/examples/gradle/library.gradle#L54-L55
I think this should be `keepattributes 'Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,EnclosingMethod'` (at least it works for me).
This is totally broken:
https://github.com/Guardsquare/proguard/blob/f509ce9efb39b4a1b22120e9b6a5043338c52afc/examples/gradle/library.gradle#L77
It works only for me if I remove `,includedescriptorclasses`.
I couldn't figure out a way yet to still apply the keep modifier `includedescriptorclasses`. As far as I looked it up, this bug is found in almost every pre-made gradle build file.

**Comment by netomi** [comment]
That is indeed a problem and needs to be fixed, thanks for the report.

**Comment by EricLafortune** [comment]
We've fixed these syntax errors for the next release (ProGuard 6.3 or 7.0).

    keepattributes 'Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,EnclosingMethod'

and

    keepclasseswithmembernames includedescriptorclasses: true, '.....'
