### ISSUE TITLE
Question about ProGuard's obfuscation

### ISSUE THREAD

**Issue by geunhayou66** [Guardsquare/proguard#113]
When proguard is used without specifying the keep in the proguard rule, 
among Android APIs, there are ones that are renamed or not.

By what factor does the renaming obfuscation be applied in Android APIs?

**Comment by mrjameshamilton** [comment]
Hi @geunhayou66 

Thanks for your question! The aim of the issue tracker here is to track technical issues and bugs.

For usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
