### ISSUE TITLE
Trying to figure out how to use this with the Sun Java Wireless Tookit

### ISSUE THREAD

**Issue by faissaloo** [Guardsquare/proguard#115]
Hey, I'm trying to obfuscate a J2ME application, the Sun Java Wireless Toolkit gives me the following instructions:
![Screenie_7](https://user-images.githubusercontent.com/8840681/104077177-89377700-5210-11eb-848a-3874900ac3d2.png)
It looks like even the oldest version archived here doesn't have a `proguard.jar` in it, might you be able to point me to the versions that people would've been using around 2008? Here's the version of j2mewtk I'm using if it helps:
![Screenie_8](https://user-images.githubusercontent.com/8840681/104077452-ab7dc480-5211-11eb-8400-a2b6283be595.png)

**Comment by mrjameshamilton** [comment]
Hi @faissaloo!

Thanks for your question! 

You can find the `proguard.jar` file inside the `lib` folder inside the release zip. For example, in 6.2.2: https://sourceforge.net/projects/proguard/files/proguard/6.2/proguard6.2.2.zip it's there and the `wtk` plugin should also be there. However, it hasn't been tested for a long time so we cannot guarantee it still works.

The aim of the issue tracker here is to track technical issues and bugs. If you have further usage questions, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.

**Comment by faissaloo** [comment]
Thanks, 6.2 didn't work (unsupported major/minor version etc) but I managed to find 4.3 on that page and that works
