### ISSUE TITLE
Gradle Plugin

### ISSUE THREAD

**Issue by lionscribe** [Guardsquare/proguard#12]
The docs at https://www.guardsquare.com/en/products/proguard/manual/gradleplugin state;

> **ProGuard Gradle Plugin**
> Alternatively, you can enable ProGuard in the Android Gradle build process using ProGuard's own tuned plugin, by changing the build.gradle file of your project as follows: ...
> 

Well, I followed the instructions, and Gradle fails with message `"Plugin with id 'proguard' not found"`.

I tried compiling the included `android-plugin` example, and it fails with same message.

I am using Android Studio 3.5.1, Gradle 5.4.1, and 'com.android.tools.build:gradle:3.5.1'

Is this a bug, or a mistake in the documentation?

**Comment by netomi** [comment]
Indeed the actual proguard plugin is missing in the release, we are fixing that asap.

**Comment by lionscribe** [comment]
While you are at it, I was testing the plugin code, and it seems that in ProguardPlugin.groovy the line
`processResources.conventionMapping.proguardOutputFile = { getAaptRulesFile(apkVariant, project) }`
does not work in Android Studio 3.51
After much headache, I was able to fix it, by casting directly to `ProcessAndroidResources `and setting the value directly
`def processResources = (ProcessAndroidResources) project.tasks.getByName("process${variantName}Resources")
if (processResources != null) {
processResources.proguardOutputFile = GradleUtil.getAaptRulesFile(apkVariant, project)
}
`

**Comment by netomi** [comment]
Fixed in 6.2.1

**Comment by netomi** [comment]
The support for the latest AGP versions will be added in a later release.
