### ISSUE TITLE
Obfuscation seems to have removed critical information from module-info.class file.

### ISSUE THREAD

**Issue by Yafei-W** [Guardsquare/proguard#127]
Hello,

Please refer to attach zip file to recreate the issue.
[ProGuardIssue.zip](https://github.com/Guardsquare/proguard/files/6016240/ProGuardIssue.zip)

The file contains two eclipse projects, TheLib and TheApp.  TheLib project contains class test.lib.TheLib which acts as a public API, class test.lib.imp.LibImp which acts as the implementation for the API, and module-info that export the public API package.  The class in the TheApp project uses the public API in the TheLib as an example.

The ideal is to use ProGuard on TheLib.jar while preserving the public API and the module-info.  TheLib.jar can be found in the TheLib/proguard folder.  In the folder there is a TheLib.cfg file for ProGuard configuration and the result jar file is the TheLibProGuarded.jar.

The issue is that as soon as obfuscation is enabled, information in the module-info.class about module is gone even if I seemed to have turned on all the "keep" settings for the module-info.  The module-info.class can be viewed by extracting the file from each jar file and open it in a HEX editor.

Is there a setting in the ProGuard that I can use so the output module-info is exactly as the input module-info without any change while obfuscation is enabled?

Tested with ProGuard 7.0.1 and Oracle JDK 11.0.11.

Thanks.

**Comment by mrjameshamilton** [comment]
Hi @Yafei-W !

It looks like you need to keep the `Module` attribute:

```
-keepattributes Module
```

Can you try this? This should keep the required module information

Note that the aim of the issue tracker here is to track technical issues and bugs. If you have further usage questions, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.

**Comment by Yafei-W** [comment]
Hi James,

The suggestion seems to work fine.

Wish it is mentioned in the document, or part of the default "Keep attributes" list in the ProGuard UI.

Thanks.

Yafei

**Comment by mrjameshamilton** [comment]
Hi @Yafei-W , indeed - you're correct! Checking it further; these should have been kept by default, so it actually is a bug.

**Comment by mrjameshamilton** [comment]
Hi @Yafei-W , this should be fixed now. You can already try this out by building ProGuard yourself (
https://github.com/Guardsquare/proguard#-building-proguard) or wait until 7.1 is released.
