### ISSUE TITLE
can't find referenced class org.jetbrains.annotations.NotNull

### ISSUE THREAD

**Issue by Matix-Media** [Guardsquare/proguard#133]
When I try to proccess my jar, I get this error:
`can't find referenced class org.jetbrains.annotations.NotNull`
how can I fix it?
It seems like it can not find the jetbrains annotations but I don't know how I can add the annotaions.

I hope someone can help me?

**Comment by mrjameshamilton** [comment]
Hi @Matix-Media !

These classes are normally compile only dependencies so they won't be in your jar/apk. 

In this case, the jetbrains annotations are not normally required by ProGuard for processing your app. You can therefore add a `-dontwarn` to your config:

```
-dontwarn org.jetbrains.annotations.**
```

Alternatively, you can add a library jar for the [jetbrains annotations](https://mvnrepository.com/artifact/org.jetbrains/annotations/20.1.0) to your configuration

```
-libraryjars /path/to/annotations.jar
```

The aim of the issue tracker here is to track technical issues and bugs. If you have further usage questions, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
