### ISSUE TITLE
Overflow of unsigned short value

### ISSUE THREAD

**Issue by SunnyYT** [Guardsquare/proguard#134]
![image](https://user-images.githubusercontent.com/25550121/110710426-be068100-81f5-11eb-8d77-f9984d7b9b49.png)
When proguard exports it causes this error, any other obfuscator does not have this error and it did not happen before so I am confused to why it happens. The input jar is fine too.

**Comment by mrjameshamilton** [comment]
Hi @SunnyYT ! Could you share the input jar, or the specific class that causes this problem so that we can investigate further?

**Comment by SunnyYT** [comment]
![image](https://user-images.githubusercontent.com/25550121/110711723-eee7b580-81f7-11eb-8bf2-e03c599c358c.png)
That is the full error, I cannot send the jar here, you have an email or something like telegram or discord where I can send the file?

**Comment by mrjameshamilton** [comment]
You can send the file to james [dot] hamilton [at] guardsquare [dot] com

**Comment by mrjameshamilton** [comment]
Hi @SunnyYT . I've received your file but I cannot reproduce the issue. 

Which ProGuard version are you using? It seems to work OK with 6.2.2 and 7.

Can you also share your configuration?

**Comment by SunnyYT** [comment]
for (File file : dependencies.listFiles()) {
                configContents.append("-libraryjars " + file.getAbsolutePath() + "\n");
            }

            configContents.append("\n" +
                    "-dontskipnonpubliclibraryclassmembers\n" +
                    "-forceprocessing\n" +
                    "-dontshrink\n" +
                    "-dontoptimize\n" +
                    "-obfuscationdictionary '" + proguardMapping.getAbsolutePath() + "'\n" +
                    "-classobfuscationdictionary '" + proguardMapping.getAbsolutePath() + "'\n" +
                    "-packageobfuscationdictionary '" + proguardMapping.getAbsolutePath() + "'\n" +
                    "-useuniqueclassmembernames\n" +
                    "-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod\n" +
                    "-keepparameternames\n" +
                    "-renamesourcefileattribute SourceFile\n" +
                    "-ignorewarnings\n" +
                    "-dontwarn\n" +
                    "\n" +
                    "\n" +
                    "-keepclassmembers,allowshrinking class * extends net.minecraft.client.gui.GuiScreen {\n" +
                    "    *** func_73863_a(...);\n" +
                    "    *** func_73864_a(...);\n" +
                    "    *** func_73869_a(...);\n" +
                    "    *** func_146286_b(...);\n" +
                    "}\n" +
                    "-keepclassmembers,allowshrinking class * extends net.minecraft.client.network.NetHandlerPlayClient {\n" +
                    "    <methods>;\n" +
                    "}\n" +
                    "# Keep - Applications. Keep all application classes, along with their 'main' methods.\n" +
                    "-keepclasseswithmembers public class * {\n" +
                    "    public static void main(java.lang.String[]);\n" +
                    "}\n" +
                    "\n" +
                    "# Also keep - Enumerations. Keep the special static methods that are required in\n" +
                    "# enumeration classes.\n" +
                    "-keepclassmembers enum  * {\n" +
                    "    public static **[] values();\n" +
                    "    public static ** valueOf(java.lang.String);\n" +
                    "}\n" +
                    "\n" +
                    "\n");

That is the config I use since I embed proguard into my jar to run everything as one jar. I use proguard 7.0.1
