### ISSUE TITLE
proguard does not produce output jar

### ISSUE THREAD

**Issue by OrenGitHub** [Guardsquare/proguard#142]
Hi guys,
Can you take a look at the [this SO question](https://stackoverflow.com/questions/66882576/proguard-does-not-create-output-jar) it would be of great help to get a feedback on what we're doing wrong. Thanks!

**Comment by mrjameshamilton** [comment]
Answered on [Guardsquare community](https://community.guardsquare.com/t/proguard-fails-to-create-output-jar/644/2).
