### ISSUE TITLE
7.1.0-beta2 fails to find JDK classes using Gradle plugin. Same project works fine with 7.1.0-beta1 

### ISSUE THREAD

**Issue by swpalmer** [Guardsquare/proguard#145]
Building with Java 8  (Zulu with JavaFX),
Gradle 6.8.3.

I get multiple errors along the lines of: " ... can't find referenced class java.lang.Object"
(same for all java.lang.* classes)

Simply changing my build to reference 7.1.0-beta1 instead and it all works again.

Gradle task is configured like this:

```
// ProGuard Obfucation
task obfuscate(type: proguard.gradle.ProGuardTask, dependsOn: jar) {
	onlyIf { project.doObfuscation }
	mustRunAfter check
	inputs.files jar
	outputs.dir file("$buildDir/proguard")
	
	injars  jar.outputs
	outjars "$buildDir/proguard/${project.name}.jar"

	// Tell ProGuard to keep the JavaFX launcher stub classes
	// com.javafx.main.*
	keep 'public class com.javafx.main.*'
	keepclassmembers 'public class com.javafx.main.* { *; }'
	printseeds "$buildDir/proguard/proguard_seeds.txt"
	printmapping "$buildDir/proguard/proguard_map.txt"
	// Use a config file for the details....
	configuration "$projectDir/proguard/proguard.pro"

	doFirst { // in a doFirst to avoid resolving configurations early
		libraryjars "$javaHome/lib/rt.jar"
		libraryjars "$javaHome/lib/jce.jar"
		libraryjars "$javaHome/lib/ext/jfxrt.jar"
			
		configurations.runtime.files.each {
			libraryjars it, filter: '!META-INF/versions/**'
		}
		configurations.compileClasspath.files.each {
			libraryjars it, filter: '!META-INF/versions/**'
		}
	}
}

```

**Comment by Username404-59** [comment]
I have the exact same issue with gradle 7.0

**Comment by mrjameshamilton** [comment]
Hi @swpalmer , @Username404-59 ! This seems to be the same issue as here: https://github.com/Guardsquare/proguard/issues/143#issuecomment-815299517

**Comment by swpalmer** [comment]
@mrjameshamilton Yes it appears to be the same issue.  However it isn't clear how to handle it.  As you can see from my comment in the build script I provided, the doFirst was necessary to avoid resolving the configurations too early which lead to other problems.  What is the right way to handle that?

**Comment by mrjameshamilton** [comment]
@swpalmer what are the other problems that you encountered? what happens if you update your config to:

```
// ProGuard Obfucation
task obfuscate(type: proguard.gradle.ProGuardTask, dependsOn: jar) {
	onlyIf { project.doObfuscation }
	mustRunAfter check
	inputs.files jar
	outputs.dir file("$buildDir/proguard")
	
	injars  jar.outputs
	outjars "$buildDir/proguard/${project.name}.jar"

	// Tell ProGuard to keep the JavaFX launcher stub classes
	// com.javafx.main.*
	keep 'public class com.javafx.main.*'
	keepclassmembers 'public class com.javafx.main.* { *; }'
	printseeds "$buildDir/proguard/proguard_seeds.txt"
	printmapping "$buildDir/proguard/proguard_map.txt"
	// Use a config file for the details....
	configuration "$projectDir/proguard/proguard.pro"

        libraryjars "$javaHome/lib/rt.jar"
	libraryjars "$javaHome/lib/jce.jar"
	libraryjars "$javaHome/lib/ext/jfxrt.jar"

        libraryjars configurations.compileClasspath, filter: '!META-INF/versions/**'
}

```

**Comment by swpalmer** [comment]
It appears to work, but then I hit #141 later on in the build as some of the compiled code is executed.

I'm not sure that I won't hit the original issue that required the doFirst... it may something that I have worked around in another way already, like replacing the primary build artifact with the obfuscated version.

**Comment by mrjameshamilton** [comment]
#141 should be fixed on master: you can build beta3 from source and install to maven local repository https://github.com/Guardsquare/proguard#-building-proguard

**Comment by mrjameshamilton** [comment]
The major refactor of the `ProGuardTask` has been rolled back for now, so this shouldn't be a problem anymore. 7.1.0-beta3 has been released.
