### ISSUE TITLE
Keep Extends doesn't work

### ISSUE THREAD

**Issue by QetzDev** [Guardsquare/proguard#158]
Hey, 

```java
import com.google.inject.AbstractModule;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;

public final class Example extends AbstractModule {
  public static Example create() {
    return new Example ();
  }

  private MasterBuildersCoreInjectModule() {}

  private static final int POOL_SIZE = 10;

  @Override
  protected void configure() {
    bind(ScheduledExecutorService.class).toInstance(Executors
      .newScheduledThreadPool(POOL_SIZE));
  }
    return GameServerMessenger.
      createWithServerTypeAndPlugin(MASTER_BUILDERS_PLUGIN_TYPE, plugin);
  }
}
```

this is my guice module and of course, I don't want the `configure()` method to be obfuscated. Therefore I have this line in my config:

```
-keep class * extends **Module {
    protected void configure();
}
```

This sadly doesn't work at all. I tried the following testwise:

```
-keep class Example {
    protected void configure();
}
```
Which worked great. As I add the extends predicate again, the method got obfuscated again.

Using: 7.0.3 and Java 15

Thanks :D

**Comment by mrjameshamilton** [comment]
Hi @QetzDev ,

Do you have the good inject classes as `-injars`/`-libraryjars`? Do you get missing class warnings for these classes?

This can happen if the `AbstractModule` is not provided as input, then the extends rulle won't work, since the search starts from the extends class.

Can you share your full config? And a build log?

**Comment by QetzDev** [comment]
Hey, 

thanks for the fast reply!

I could solve the problem by adding the missing library jar, thanks! 

Have a great day
