### ISSUE TITLE
Proguard 6.2.2: Unsupported version number [55.0]

### ISSUE THREAD

**Issue by valeriyo** [Guardsquare/proguard#160]
I'm using `net.sf.proguard:proguard-gradle:6.2.2` and switched from Java 1.8 to 11. Now I'm getting 

```
java.io.IOException: Can't read [......jar] (Can't process class [.....class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))
```

I thought ProGuard 6.2.2 supported Java 11 ?

**Comment by mrjameshamilton** [comment]
Hi @valeriyo , I think you're right that 6.2.2 should have supported 11, so I'm not sure what happened there. 

But 6.2.2 is not in development anymore. Can you update to 7.0.1 or 7.1.0-beta3?

**Comment by valeriyo** [comment]
The latest version I see is `6.3.0beta1` --- https://mvnrepository.com/artifact/net.sf.proguard/proguard-gradle

**Comment by mrjameshamilton** [comment]
The group name changed since 7.0.0 to `com.guardsquare`: https://mvnrepository.com/artifact/com.guardsquare/proguard-gradle

**Comment by valeriyo** [comment]
Hmmm... even if I comment out these:

```
  dependencies {
    classpath("com.android.tools.build:gradle:3.3.0")
    classpath("com.guardsquare:proguard-gradle:7.0.1")
  }
```

This task runs (and fails with the error above):
```
  val proguard2 = register<proguard.gradle.ProGuardTask>("proguard2") {
     ...
  }
```

So, it's pulling the `proguard.gradle.ProGuardTask` from somewhere else? I'm stumped.

**Comment by valeriyo** [comment]
ok it looks like it's pulling `net.sf.proguard:proguard-gradle:6.0.3` from `com.android.tools.build:gradle:3.3.0`

**Comment by valeriyo** [comment]
added module substitution:
```
buildscript {
  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath("com.android.tools.build:gradle:3.3.0")
  }

  configurations.all {
    resolutionStrategy {
      dependencySubstitution {
        substitute(module("net.sf.proguard:proguard-gradle")).with(module("com.guardsquare:proguard-gradle:7.0.1"))
      }
    }
  }
}

```

now the `buildEnvironment` looks correct:

```
classpath
+--- com.android.tools.build:gradle:3.3.0
   ...
|    +--- net.sf.proguard:proguard-gradle:6.0.3 -> com.guardsquare:proguard-gradle:7.0.1
|    |    +--- com.guardsquare:proguard-base:7.0.1
|    |    |    +--- com.guardsquare:proguard-core:7.0.1
|    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.4.20 (*)
|    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.31 -> 1.4.20
|    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.1.0
|    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.4.20 (*)
|    |    |    \--- com.google.code.gson:gson:2.8.5
|    |    +--- com.guardsquare:proguard-core:7.0.1 (*)
|    |    \--- com.android.tools.build:gradle:3.0.0 -> 3.3.0 (*)
```

However, when I run the `assemble` target, I still hit the same error:

```
* What went wrong:
Execution failed for task ':sdk_core_jvm:library:proguard2'.
> java.io.IOException: Can't read [.../jmods/java.base.jmod(;;;;;;;!module-info.class)] (Can't process class [apple/security/KeychainStore$TrustedCertEntry.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))
```

This is insane.

**Comment by valeriyo** [comment]
@mrjameshamilton any help?

**Comment by mrjameshamilton** [comment]
It looks like to the dependencies are correct. 6.0.3 was replaced by 7.0.1, so that's strange that the wrong one is still executed.

Can you check the build log with --info, the proguard version number is printed during processing.

You can also try adding an exclude for the android tools classpath e.g.

```
dependencies {
    classpath("com.android.tools.build:gradle:3.3.0") {
        exclude group: 'net.sf.proguard', module: 'proguard-gradle'
    }
}
```

**Comment by valeriyo** [comment]
It's "ProGuard, version 6.0.3" even though the `buildEnvironment` uses 7.0.1 😠

**Comment by mrjameshamilton** [comment]
Are you able to reproduce the problem in a smaller example and share it?

**Comment by avently** [comment]
In my case I have this buildEnvironment dependencies:

```

+--- com.guardsquare:proguard-gradle:7.1.1                                                                                                                                       
|    \--- com.guardsquare:proguard-base:7.1.1                                                                                                                                    
|         +--- com.google.code.gson:gson:2.8.5 -> 2.8.6                                                                                                                          
|         \--- com.guardsquare:proguard-core:7.1.1                                                                                                                               
|              +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 -> 1.5.21                                                                                                          
|              |    +--- org.jetbrains:annotations:13.0                                                                                                                          
|              |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.21                                                                                                        
|              +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72 -> 1.5.21                                                                                                   
|              \--- org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.1.0                                                                                                             
|                   \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.5.21 (*) 

```

but still `ProGuard, version 6.0.3`

Task: 
```groovy
task asRelease(type: proguard.gradle.ProGuardTask, dependsOn: 'prepareRelease') {
    configuration 'proguard-rules.pro'

    injars "$buildDir/libs/app-jvm-${version}.jar"
    outjars "jars/debug/app-${version}.jar"
    if (System.getProperty('java.version').startsWith('1.')) {
        libraryjars "${System.getProperty('java.home')}/lib/rt.jar"
    } else {
        libraryjars "${System.getProperty('java.home')}/jmods/java.base.jmod", jarfilter: '!**.jar', filter: '!module-info.class'
    }
}
```


After some experiments I found that Gradle reads top level project which has an Android target. The target doesn't include proguard in dependecies but has gradle plugin included. So I just specified proguard plugin in Android project and now I see a correct version of proguard, so issue is fixed.

```groovy 
dependencies {
classpath "com.guardsquare:proguard-gradle:$proguard_version"
...
}
```

**Comment by waseefakhtar** [comment]
> added module substitution:
> 
> ```
> buildscript {
>   repositories {
>     google()
>     mavenCentral()
>   }
> 
>   dependencies {
>     classpath("com.android.tools.build:gradle:3.3.0")
>   }
> 
>   configurations.all {
>     resolutionStrategy {
>       dependencySubstitution {
>         substitute(module("net.sf.proguard:proguard-gradle")).with(module("com.guardsquare:proguard-gradle:7.0.1"))
>       }
>     }
>   }
> }
> ```
> 
> now the `buildEnvironment` looks correct:
> 
> ```
> classpath
> +--- com.android.tools.build:gradle:3.3.0
>    ...
> |    +--- net.sf.proguard:proguard-gradle:6.0.3 -> com.guardsquare:proguard-gradle:7.0.1
> |    |    +--- com.guardsquare:proguard-base:7.0.1
> |    |    |    +--- com.guardsquare:proguard-core:7.0.1
> |    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.4.20 (*)
> |    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.31 -> 1.4.20
> |    |    |    |    \--- org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.1.0
> |    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.4.20 (*)
> |    |    |    \--- com.google.code.gson:gson:2.8.5
> |    |    +--- com.guardsquare:proguard-core:7.0.1 (*)
> |    |    \--- com.android.tools.build:gradle:3.0.0 -> 3.3.0 (*)
> ```
> 
> However, when I run the `assemble` target, I still hit the same error:
> 
> ```
> * What went wrong:
> Execution failed for task ':sdk_core_jvm:library:proguard2'.
> > java.io.IOException: Can't read [.../jmods/java.base.jmod(;;;;;;;!module-info.class)] (Can't process class [apple/security/KeychainStore$TrustedCertEntry.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))
> ```
> 
> This is insane.

Took me two days to fix this and this is what worked for me!
