### ISSUE TITLE
The -adaptresourcefilenames does not work

### ISSUE THREAD

**Issue by meshcow** [Guardsquare/proguard#162]
The problem was [initaillay described](https://community.guardsquare.com/t/how-is-adaptresourcefilenames-supposed-to-work/733) in your community resources forum. Making an issue out of it, as it got no answers there.

Shortly, for the .jar with the structure
```
├── META-INF
│   ├── MANIFEST.MF
│   └── notes
│       └── com.my.company.app.HelloWorld  <-- contains "com.my.company.app.HelloWorld"
└── com
    └── my
        └── company
            └── app
                └── HelloWorld.class
```
after running "java -jar proguard-base-6.2.2.jar @my.pro” with the following config: 
```
-libraryjars <java.home>/lib/rt.jar
-injars       my.jar
-outjars      my-obf.jar
-printmapping obfuscation.map
-adaptresourcefilecontents META-INF/notes/*
-adaptresourcefilenames META-INF/notes/*
-dontoptimize
-dontshrink
```
the resulting .jar contains the class file renamed (as expected), resource file content obfuscated (as expected), but not renamed:
```
├── META-INF
│   ├── MANIFEST.MF
│   └── notes
│       └── com.my.company.app.HelloWorld  <-- contains "a.a.a.a.a"
└── a
    └── a
        └── a
            └── a
                └── a.class
```
According to [documentation of -adaptresourcefilenames](https://www.guardsquare.com/manual/configuration/usage#adaptresourcefilenames), the file "META-INF/notes/com.my.company.app.HelloWorld" should be renamed to "META-INF/notes/a.a.a.a.a" (the name of the corresponding renamed class), but this doesn't happen.

All artifacts mentioned above are attached to this issue report
 
[artifacts.zip](https://github.com/Guardsquare/proguard/files/6478119/artifacts.zip)

**Comment by mrjameshamilton** [comment]
See community answer https://community.guardsquare.com/t/how-is-adaptresourcefilenames-supposed-to-work/733/2
