### ISSUE TITLE
issue running in VM with single processor

### ISSUE THREAD

**Issue by paulwoods222** [Guardsquare/proguard#173]
I'm running 7.1.0-beta5 on a VM with only one processor assigned. 
Proguard is failing in InfluenceFixpointVisitor.java where the number of threads to use is set as:

Runtime.getRuntime().availableProcessors() -1

A check should be made to test the final number of threads is > 0

     [proguard]   Final number of program classes:               336
     [proguard] Optimizing (pass 1/1)...
     [proguard] java.lang.IllegalArgumentException
     [proguard]     at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1295)
     [proguard]     at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1217)
     [proguard]     at java.base/java.util.concurrent.Executors.newFixedThreadPool(Executors.java:155)
     [proguard]     at proguard.optimize.InfluenceFixpointVisitor.<init>(InfluenceFixpointVisitor.java:66)
     [proguard]     at proguard.optimize.Optimizer.execute(Optimizer.java:566)
     [proguard]     at proguard.ProGuard.optimize(ProGuard.java:546)
     [proguard]     at proguard.ProGuard.execute(ProGuard.java:191)
     [proguard]     at proguard.ProGuard.main(ProGuard.java:715)

**Comment by mrjameshamilton** [comment]
Hi @paulwoods222 ! Thanks for the report. Indeed, you're correct that a check should be made for the number of threads.

**Comment by rubenpieters** [comment]
Should be fixed by https://github.com/Guardsquare/proguard/commit/847683d5eeb8b18aae45854793dd4efb0a9deed0 .
