### ISSUE TITLE
java code obfuscation related In the Android project

### ISSUE THREAD

**Issue by jackkong1222** [Guardsquare/proguard#177]
Hello, I recently encountered a problem. Android applications are compiled with confusion, sometimes there is a problem of variable duplicate names in the same domain (abnormal display at runtime).The problem disappears after a recompilation. 
My question is why variables with different names appear duplicate names after code confusion? How to solve it? How to avoid similar problems in the future? Thank you very much.

**Comment by mrjameshamilton** [comment]
Hi @jackkong1222  !

Thanks for your question! The aim of the issue tracker here is to track technical issues and bugs.

For usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
