### ISSUE TITLE
Obfuscation does not work

### ISSUE THREAD

**Issue by priyankaghule2906** [Guardsquare/proguard#178]
not able to see any obfuscated jar under the build/lib folder

**Comment by mrjameshamilton** [comment]
Hi @priyankaghule2906 !

Thanks for your question! The aim of the issue tracker here is to track technical issues and bugs.

For usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
