### ISSUE TITLE
Parameterless constructor might be made private when another constructor has its parameters removed

### ISSUE THREAD

**Issue by netomi** [Guardsquare/proguard#18]
When a class has multiple constructors it can happen that for some of them, unused parameters are removed. When several constructors have the same descriptor afterwards, ProGuard has to fix that by introducing some synthetic parameters to distinguish them from another.

Now this can lead to situations where the constructor whose parameter has been removed will become the new parameterless constructor, and the original constructor has some additional parameter.

This can have multiple effects: the original parameterless constructor might be made private, and a different constructor might be called when the class is dynamically created.

A simple example to illustrate the problem is this kotlin class:

```
class MyService(
private val foo: String = "bar",
private val bar: Intent = Intent()
) : Service() {
override fun onBind(intent: Intent?): IBinder? = null
}
```

As there are default values, the kotlin compiler will create additional synthetic constructors whose parameters might get removed.

When using Proguard on the class with optimization enabled, the original parameterless constructor is made private.

**Comment by netomi** [comment]
The problem lies in the DuplicateInvocationFixer that is run after parameters have been removed.
The fixer checks if there are multiple constructors with the same descriptor, and fixes it by adding an additional parameter to one of these constructors. Unfortunately the there is no precedence which constructor gets modified, the one that has parameters removed in the step before should be used to avoid such problems.

**Comment by mrjameshamilton** [comment]
Fixed here: https://github.com/Guardsquare/proguard/commit/2ba28f1a1786a472c373346001f91c61a5711006#diff-a3b4b7dcd9ccf1d13a4ff3d3127bafbe93b6095a36e13b8966a97b4196e580dfR94
