### ISSUE TITLE
Provide full Gradle example of .war minification

### ISSUE THREAD

**Issue by Anthony-Gaudino** [Guardsquare/proguard#185]
In [Proguard documentation](https://www.guardsquare.com/manual/troubleshooting/troubleshooting#unexpectedclass) it says:

> The given class file contains a definition for the given class, but the directory name of the file doesn't correspond to the package name of the class. ProGuard will accept the class definition, but the current implementation will not write out the processed version. Please make sure your input classes are packaged correctly. Notably, class files that are in the WEB-INF/classes directory in a war should be packaged in a jar and put in the WEB-INF/lib directory. If you don't mind these classes not being written to the output, you can specify the -ignorewarnings option, or even the -dontwarn option.

Can you please provide a full Gradle example of minification using Proguard, showing how one can pack what's in the `WEB-INF/classes` directory into a `.jar` and add it into the `lib` directory as said there.

**Comment by mrjameshamilton** [comment]
Hi @Anthony-Gaudino ! Thanks for the question.  We don't currently have an example for this but, for usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get help with your configuration from our team of engineers and skilled community members.
