### ISSUE TITLE
`can't find referenced class ?`

### ISSUE THREAD

**Issue by boris-petrov** [Guardsquare/proguard#187]
[Here is a reproduction](https://github.com/boris-petrov/proguard-jdk16-bug/tree/another-bug). Note that it's a specific branch of the repo. The `master` branch is for a [different issue](https://github.com/Guardsquare/proguard/issues/181).

Running `gradle proguardWar` on that branch leads to:

```
% gradle proguardWar
> Task :compileJava
> Task :compileGroovy
> Task :processResources NO-SOURCE
> Task :classes

> Task :proguardWar FAILED
Note: there were 138 duplicate class definitions.
      (https://www.guardsquare.com/proguard/manual/troubleshooting#duplicateclass)
Warning: com.company.servlets.Seed$_getData_closure1: can't find referenced class ?
Warning: com.company.servlets.Seed$_getData_closure1: can't find referenced class ?
Warning: there were 2 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedclass)
Warning: optimization is enabled while shrinking is disabled.
         You need to remove the option -dontshrink or optimization might result in classes that fail verification at runtime.
```

The interesting thing is that if you change Groovy's version from 3.0.9 to 3.0.8 in `build.gradle` (line 20) - the error goes away and the task completes successfully. I believe this is a bug in ProGuard.

**Comment by mrjameshamilton** [comment]
Hi @boris-petrov !

This seems to be a Groovy bug. The source of the error is a `Signature` attribute for the method `doCall();`  in `com/company/servlets/Seed$_getData_closure1`. There is a question mark in the attribute for a class name which seems like a bug in Groovy.

```
  public java.util.List<java.util.Map<java.lang.String, ?>> doCall();
    descriptor: ()Ljava/util/List;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: aconst_null
         2: invokevirtual #54                 // Method doCall:(Ljava/lang/Object;)Ljava/util/List;
         5: areturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       6     0  this   Lcom/company/servlets/Seed$_getData_closure1;
    Signature: #59                          // ()Ljava/util/List<Ljava/util/Map<Ljava/lang/String;L?;>;>;

```

**Comment by boris-petrov** [comment]
@mrjameshamilton - thanks for the response! I [opened](https://issues.apache.org/jira/browse/GROOVY-10229) an issue in their bugtracker. Let's see what they say. I'll close this issue here after they acknowledge that the problem is on their side if that's fine with you.

**Comment by boris-petrov** [comment]
So it really is a Groovy bug and I believe they've already fixed it. Thanks for the support!
