### ISSUE TITLE
Can't build proguard with either javac v11 or v16 on Linux

### ISSUE THREAD

**Issue by Shamus397** [Guardsquare/proguard#188]
This is with a fresh copy of the current git head (121ac840a766096a2899015f4331198b70cabf9b).  Compilation fails with the following error (proguard-core git head [1819267d15697c61bf28a1adc53128b6f5f73774] builds just fine):

./gradlew --include-build=../proguard-core assemble
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :base:compileJava
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/shrink/ClassUsageMarker.java:1947: error: cannot find symbol
                                       KotlinMetadataAnnotation annotation)
                                       ^
  symbol:   class KotlinMetadataAnnotation
  location: class ClassUsageMarker.KotlinUsageMarker
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/util/kotlin/asserter/constraint/KmAnnotationIntegrity.java:81: error: cannot find symbol
    public void visitAnyAnnotation(Clazz clazz, KotlinMetadataAnnotation antn)
                                                ^
  symbol:   class KotlinMetadataAnnotation
  location: class KmAnnotationIntegrity
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/obfuscate/kotlin/KotlinValueParameterUsageMarker.java:61: error: cannot find symbol
                                                  new AllKotlinPropertiesVisitor(this));
                                                      ^
  symbol:   class AllKotlinPropertiesVisitor
  location: class KotlinValueParameterUsageMarker
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/obfuscate/kotlin/KotlinValueParameterNameShrinker.java:115: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/obfuscate/Obfuscator.java:536: error: cannot find symbol
                new AllFunctionsVisitor(
                    ^
  symbol:   class AllFunctionsVisitor
  location: class Obfuscator
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/obfuscate/Obfuscator.java:624: error: cannot find symbol
                new AllKotlinPropertiesVisitor(
                    ^
  symbol:   class AllKotlinPropertiesVisitor
  location: class Obfuscator
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/shrink/ClassUsageMarker.java:1515: error: ClassUsageMarker.KotlinUsageMarker is not abstract and does not override abstract method visitAnyAnnotation(Clazz,KotlinAnnotatable,KotlinAnnotation) in KotlinAnnotationVisitor
    public class KotlinUsageMarker
           ^
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/shrink/ClassUsageMarker.java:1945: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/util/kotlin/asserter/constraint/FunctionIntegrity.java:41: error: cannot find symbol
        kotlinMetadata.accept(clazz, new AllFunctionsVisitor(this));
                                         ^
  symbol:   class AllFunctionsVisitor
  location: class FunctionIntegrity
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/util/kotlin/asserter/constraint/PropertyIntegrity.java:39: error: cannot find symbol
        kotlinMetadata.accept(clazz, new AllKotlinPropertiesVisitor(this));
                                         ^
  symbol:   class AllKotlinPropertiesVisitor
  location: class PropertyIntegrity
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/util/kotlin/asserter/constraint/ConstructorIntegrity.java:36: error: cannot find symbol
        kotlinMetadata.accept(clazz, new AllConstructorsVisitor(this));
                                         ^
  symbol:   class AllConstructorsVisitor
  location: class ConstructorIntegrity
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/util/kotlin/asserter/constraint/KmAnnotationIntegrity.java:31: error: KmAnnotationIntegrity is not abstract and does not override abstract method visitAnyAnnotation(Clazz,KotlinAnnotatable,KotlinAnnotation) in KotlinAnnotationVisitor
public class KmAnnotationIntegrity
       ^
/home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/util/kotlin/asserter/constraint/KmAnnotationIntegrity.java:80: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /home/shamus/source/java-deobfuscate/proguard/base/src/main/java/proguard/OutputWriter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors

> Task :base:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:compileJava'.
> Compilation failed; see the compiler error output for details.

There doesn't seem to be any definition of KotlinMetadataAnnotation anywhere in either proguard or proguard-core:

$ grep -nr "KotlinMetadataAnnotation" ../proguard-core/*
../proguard-core/src/test/kotlin/proguard/classfile/kotlin/KotlinMetadataAnnotationTest.kt:49:class KotlinMetadataAnnotationTest : FreeSpec({
../proguard-core/src/main/java/proguard/classfile/util/ClassReferenceInitializer.java:1111:        // Implementations for KotlinMetadataAnnotationVisitor
../proguard-core/src/main/java/proguard/classfile/util/ClassReferenceInitializer.java:1123:        // Implementations for KotlinMetadataAnnotationArgumentVisitor
$ grep -nr "KotlinMetadataAnnotation" ./*
./base/src/main/java/proguard/shrink/ClassUsageMarker.java:1947:                                       KotlinMetadataAnnotation annotation)
./base/src/main/java/proguard/util/kotlin/asserter/constraint/KmAnnotationIntegrity.java:81:    public void visitAnyAnnotation(Clazz clazz, KotlinMetadataAnnotation antn)
./base/src/main/java/proguard/ProGuard.java:145:                stripKotlinMetadataAnnotations();
./base/src/main/java/proguard/ProGuard.java:352:    private void stripKotlinMetadataAnnotations()

**Comment by mrjameshamilton** [comment]
Hi @Shamus397 ! 

ProGuardCORE has had some active development recently to support Kotlin 1.5 in ProGuard, among other things. Those were breaking changes to the ProGuardCORE API. 

ProGuard master branch can be built against the [v7.1.1 tag](https://github.com/Guardsquare/proguard-core/tree/v7.1.1) and ProGuard [beta](https://github.com/Guardsquare/proguard/tree/beta) branch can be built against the master branch of ProGuardCORE.

**Comment by Shamus397** [comment]
Can confirm building from the tagged v7.1.1 release of both ProGuard and ProGuardCORE works as advertised.  Thanks.
