### ISSUE TITLE
Invoke does not work in Java 16 proguard

### ISSUE THREAD

**Issue by MisterCow1** [Guardsquare/proguard#189]
I have a Fabric 1.17.1 (Java 16) mod for Minecraft that I am trying to obfuscate. Included with this mod is my event system that handles all the events for my mod. This event system uses the invoke method to call events in my event listener class at runtime.

Here is the the event I am calling using the call method:

```
@EventHandler
public static void onMinecraftInitialization(EventMinecraftInitialization event)
{
    // Do stuff
}
```

Here is the call method:

```
public void call(Event event)
{
    final EventData data = get(event.getClass());

    try
    {
        data.target.invoke(data.source, event); // Error here
    }
    catch (InvocationTargetException | IllegalAccessException e)
    {
        e.printStackTrace();
    }
}
```

I am also using mixins to register my event listener class, which works fine.

In a development enviroment this works fine and my minecraft mod runs. However, when I build my mod and attempt to use it in the Minecraft launcher it crashed, with the crash report of:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    dev/mistercow1/sobyity/EventBus.call(Ldev/mistercow1/sobyity/Event;)V @33: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 
    'java/lang/ReflectiveOperationException'
```

`dev/mistercow1/sobyity/EventBus.call(Ldev/mistercow1/sobyity/Event;)V @33` is the invoke in my call method.

In my proguard mappings I have excluded the event library and the mixin package (so they do not get obfuscated), as that is required for minecraft to run, as it is packaged into the jar using shadowjar. I have also disabled shrinking and optimizing, and repackaged classes into the base directory (dev.mistercow1.minecraftmod)

Everything works fine in the deobfuscated version of my mod and in the development enviroment, so I am confused why the obfuscated version does not work.

I have already tried using `data.target.invoke(null, event);` instead, but it has no effect.

Is this a problem with proguard or my event system or minecraft mod?

Does anyone have any solutions?

**Comment by mrjameshamilton** [comment]
Hi @MisterCow1 !

As a test, if you also use `-dontobfuscate` does the problem disappear? You mention you have already disabled optimization and shrinking, so this would also rule out or confirm obfuscation as well.

Have you tried adding a keep rule for `dev/mistercow1/sobyity/EventBus.call(Ldev/mistercow1/sobyity/Event;)V` ?

Could you show the bytecode of `dev/mistercow1/sobyity/EventBus.call(Ldev/mistercow1/sobyity/Event;)V` - you can print it with `javap -c -v -p -cp my.jar dev.mistercow1.sobyity.EventBus`

**Comment by MisterCow1** [comment]
I have added `-dontobfuscate` and it seems like Minecraft still crashes with the `java.lang.VerifyError: Bad type on operand stack` error.

`dev/mistercow1/sobyity/EventBus.call(Ldev/mistercow1/sobyity/Event;)V` is being kept, along with the entire sobyity library. My Minecraft mod is separate from this, but sobyity is included in the jar, unobfuscted.

Bytecode for `dev/mistercow1/sobyity/EventBus.call(Ldev/mistercow1/sobyity/Event;)V` is as follows:

`public void call(dev.mistercow1.sobyity.Event);
    descriptor: (Ldev/mistercow1/sobyity/Event;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=6, locals=4, args_size=2
         0: aload_1
         1: invokevirtual #22                 // Method java/lang/Object.getClass:()Ljava/lang/Class;
         4: invokestatic  #17                 // Method get:(Ljava/lang/Class;)Ldev/mistercow1/sobyity/EventData;
         7: astore_2
         8: aload_2
         9: getfield      #16                 // Field dev/mistercow1/sobyity/EventData.target:Ljava/lang/reflect/Method;
        12: aload_2
        13: getfield      #15                 // Field dev/mistercow1/sobyity/EventData.source:Ljava/lang/Class;
        16: iconst_1
        17: anewarray     #8                  // class java/lang/Object
        20: dup
        21: iconst_0
        22: aload_1
        23: aastore
        24: invokevirtual #26                 // Method java/lang/reflect/Method.invoke:(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
        27: pop
        28: goto          36
        31: astore_3
        32: aload_3
        33: invokevirtual #23                 // Method java/lang/ReflectiveOperationException.printStackTrace:()V
        36: return
      Exception table:
         from    to  target type
             8    28    31   Class java/lang/reflect/InvocationTargetException
             8    28    31   Class java/lang/IllegalAccessException
      StackMapTable: number_of_entries = 2
        frame_type = 255 /* full_frame */
          offset_delta = 31
          locals = []
          stack = [ class java/lang/Object ]
        frame_type = 4 /* same */`

**Comment by mrjameshamilton** [comment]
It looks like the type in the `StackMapTable` is wrong - at offset 31 there should be an exception on the stack since that's the start of the exception handler. This could be a problem with the preverifier since that's where these stack map tables are generated in ProGuard.

* Can you show the original bytecode of this method?
* Can you try adding `-dontpreverify` and show the bytecode?

**Comment by MisterCow1** [comment]
Original bytecode for call method is as follows:

`public void call(dev.mistercow1.sobyity.Event);
    descriptor: (Ldev/mistercow1/sobyity/Event;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=6, locals=4, args_size=2
         0: aload_1
         1: invokevirtual #98                 // Method java/lang/Object.getClass:()Ljava/lang/Class;
         4: invokestatic  #100                // Method get:(Ljava/lang/Class;)Ldev/mistercow1/sobyity/EventData;
         7: astore_2
         8: aload_2
         9: getfield      #72                 // Field dev/mistercow1/sobyity/EventData.target:Ljava/lang/reflect/Method;
        12: aload_2
        13: getfield      #103                // Field dev/mistercow1/sobyity/EventData.source:Ljava/lang/Class;
        16: iconst_1
        17: anewarray     #4                  // class java/lang/Object
        20: dup
        21: iconst_0
        22: aload_1
        23: aastore
        24: invokevirtual #107                // Method java/lang/reflect/Method.invoke:(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
        27: pop
        28: goto          36
        31: astore_3
        32: aload_3
        33: invokevirtual #114                // Method java/lang/ReflectiveOperationException.printStackTrace:()V
        36: return
      Exception table:
         from    to  target type
             8    28    31   Class java/lang/reflect/InvocationTargetException
             8    28    31   Class java/lang/IllegalAccessException
      StackMapTable: number_of_entries = 2
        frame_type = 255 /* full_frame */
          offset_delta = 31
          locals = [ class dev/mistercow1/sobyity/EventBus, class dev/mistercow1/sobyity/Event, class dev/mistercow1/sobyity/EventData ]
          stack = [ class java/lang/ReflectiveOperationException ]
        frame_type = 4 /* same */
      LineNumberTable:
        line 166: 0
        line 171: 8
        line 176: 28
        line 173: 31
        line 175: 32
        line 177: 36
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
           32       4     3     e   Ljava/lang/ReflectiveOperationException;
            0      37     0  this   Ldev/mistercow1/sobyity/EventBus;
            0      37     1 event   Ldev/mistercow1/sobyity/Event;
            8      29     2  data   Ldev/mistercow1/sobyity/EventData;`



Bytecode with `-dontpreverify` is as follows:

`public void call(dev.mistercow1.sobyity.Event);
    descriptor: (Ldev/mistercow1/sobyity/Event;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=6, locals=4, args_size=2
         0: aload_1
         1: invokevirtual #20                 // Method java/lang/Object.getClass:()Ljava/lang/Class;
         4: invokestatic  #15                 // Method get:(Ljava/lang/Class;)Ldev/mistercow1/sobyity/EventData;
         7: astore_2
         8: aload_2
         9: getfield      #14                 // Field dev/mistercow1/sobyity/EventData.target:Ljava/lang/reflect/Method;
        12: aload_2
        13: getfield      #13                 // Field dev/mistercow1/sobyity/EventData.source:Ljava/lang/Class;
        16: iconst_1
        17: anewarray     #6                  // class java/lang/Object
        20: dup
        21: iconst_0
        22: aload_1
        23: aastore
        24: invokevirtual #24                 // Method java/lang/reflect/Method.invoke:(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
        27: pop
        28: goto          36
        31: astore_3
        32: aload_3
        33: invokevirtual #21                 // Method java/lang/ReflectiveOperationException.printStackTrace:()V
        36: return
      Exception table:
         from    to  target type
             8    28    31   Class java/lang/reflect/InvocationTargetException
             8    28    31   Class java/lang/IllegalAccessException`

**Comment by EricLafortune** [comment]
The problem is that ProGuard outputs `e` as `Object` instead of `ReflectiveOperationException` in the preverification attribute, which then upsets the java verifier.

Did ProGuard complain about not finding common superclasses, and did you then add ProGuard options `-ignorewarnings` or `-dontwarn` to get around these warnings? This could lead to problems if some classes are missing from the input. For example, Java 6 didn't have `ReflectiveOperationException` yet. Are you specifying the proper version of the Java runtime with `-libraryjars`?

**Comment by MisterCow1** [comment]
Adding the jmods to `-libraryjars` fixed the issue, thanks!

**Comment by Bais-dynavla** [comment]
> Adding the jmods to `-libraryjars` fixed the issue, thanks!

Hello, I’m developing a fabric mod and encountered the same problem after using ProGuard for obfuscation. I want to know what you mean by “jmods”? Here is my error report, obfuscation task, and obfuscation rules. Please help me solve this problem, thank you!

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    bais/dynaval/util/render/b.loadBedFootPoint(Lnet/minecraft/class_630;)V @515: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/ReflectiveOperationException'
  Current Frame:
    bci: @515
    flags: { }
    locals: { top, top, 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 014c 1237 1207 b600 5a4c 2b04 b600 632b
    0000010: 2ab6 0062 c000 2e4d 014e 2cb9 0075 0100
    0000020: b900 7601 003a 0419 04b9 0070 0100 9901
    0000030: d019 04b9 0071 0100 c000 2a3a 052c 1905
    0000040: b900 7402 00c0 0037 3a06 1237 1208 b600
    0000050: 5a4e 2d04 b600 632d 1906 b600 62c0 002d
    0000060: 3a07 1907 b900 7301 003a 0819 08b9 0070
    0000070: 0100 9901 8919 08b9 0071 0100 c000 3a3a
    0000080: 0912 3a12 06b6 005a 3a0a 190a 04b6 0063
    0000090: 190a 1909 b600 62c0 001f 3a0b 190b 3a0c
    00000a0: 190c be36 0d03 360e 150e 150d a201 4c19
    00000b0: 0c15 0e32 3a0f 190f b400 543a 1019 103a
    00000c0: 1119 11be 3612 0336 1315 1315 12a2 0125
    00000d0: 1911 1513 323a 1419 14b4 0057 b600 6d12
    00000e0: 046e 3815 1914 b400 57b6 006e 1204 6e38
    00000f0: 1619 14b4 0057 b600 6f12 046e 3817 1905
    0000100: 120a b600 6099 0032 bb00 3259 1715 8d17
    0000110: 168d 1717 8db7 0066 1202 b600 673a 1819
    0000120: 18b4 0051 9038 1519 18b4 0050 9038 1619
    0000130: 18b4 004f 9038 1719 0512 0cb6 0060 9900
    0000140: 37bb 0032 5917 158d 1716 8d17 178d b700
    0000150: 6612 02b6 0067 1201 b600 683a 1819 18b4
    0000160: 0051 9038 1519 18b4 0050 9038 1619 18b4
    0000170: 004f 9038 17bb 0032 5917 158d 1716 8d17
    0000180: 178d b700 6612 02b6 0067 3a18 1918 b400
    0000190: 5190 3815 1918 b400 5090 3816 1918 b400
    00001a0: 4f90 3817 08bd 0028 5903 1715 b800 5cb8
    00001b0: 005b 5359 0417 16b8 005c b800 5b53 5905
    00001c0: 1717 b800 5cb8 005b 5359 0619 14b4 0056
    00001d0: b800 5b53 5907 1914 b400 55b8 005b 533a
    00001e0: 19b2 003e 1919 b900 7202 0057 8413 01a7
    00001f0: feda 840e 01a7 feb3 a7fe 73a7 fe2c a700
    0000200: 084d 2cb6 005e b1                      
  Exception Handler Table:
    bci [2, 510] => handler: 513
    bci [2, 510] => handler: 513
  Stackmap Table:
    full_frame(@39,{Top,Top,Object[#46],Top,Object[#44]},{})
    full_frame(@107,{Top,Top,Object[#46],Top,Object[#44],Object[#42],Top,Top,Object[#44]},{})
    full_frame(@168,{Top,Top,Object[#46],Top,Object[#44],Object[#42],Top,Top,Object[#44],Top,Top,Top,Object[#31],Integer,Integer},{})
    full_frame(@201,{Top,Top,Object[#46],Top,Object[#44],Object[#42],Top,Top,Object[#44],Top,Top,Top,Object[#31],Integer,Integer,Top,Top,Object[#32],Integer,Integer},{})
    full_frame(@311,{Top,Top,Object[#46],Top,Object[#44],Object[#42],Top,Top,Object[#44],Top,Top,Top,Object[#31],Integer,Integer,Top,Top,Object[#32],Integer,Integer,Object[#57],Float,Float,Float},{})
    same_frame(@373)
    full_frame(@498,{Top,Top,Object[#46],Top,Object[#44],Object[#42],Top,Top,Object[#44],Top,Top,Top,Object[#31],Integer,Integer},{})
    full_frame(@504,{Top,Top,Object[#46],Top,Object[#44],Object[#42],Top,Top,Object[#44]},{})
    full_frame(@507,{Top,Top,Object[#46],Top,Object[#44]},{})
    full_frame(@510,{},{})
    same_locals_1_stack_item_frame(@513,Object[#40])
    same_frame(@518)

	at bais.dynaval.util.render.g.loadEntityModel(EntityRenderModel.java:181)
	at net.minecraft.class_310.handler$zhc000$dyna_val_mod$render(class_310.java:3265)
	at net.minecraft.class_310.method_1481(class_310.java)
	at net.minecraft.class_634.method_11120(class_634.java:414)
	at net.minecraft.class_2678.method_11567(class_2678.java:57)
	at net.minecraft.class_2678.method_11054(class_2678.java:14)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

```


```
task proguardJar(type: proguard.gradle.ProGuardTask) {
	configuration 'proguard-rules.pro'  

	injars 'build/libs/test-1.0.0.jar'  
	outjars 'build/libs/test-1.0.0.0.jar'  

	libraryjars "${System.getProperty('java.home')}/lib/rt.jar"  
	libraryjars configurations.runtimeClasspath  


	doLast {
		println 'ProguardJar'
	}
}
```


```
-dontshrink

-dontoptimize

-dontusemixedcaseclassnames

-ignorewarnings
-dontwarn

-keepattributes
Exceptions
,InnerClass
,Deprecated
,SourceFile
,LineNumberTable
,*Annotation*
,Synthetic
,EnclosingMethod
,Signature
,ReflectiveOperationException

-libraryjars C:\Users\Tutu\Desktop\DynaVal\.gradle\loom-cache\minecraftMaven\net\minecraft\minecraft-clientOnly-56a904ae86\1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2\minecraft-clientOnly-56a904ae86-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar


-keeppackagenames



-keep public class bais.dynaval.mixin.*

-keep public class bais.dynaval.*

-keepclassmembers class * {
    <methods>;
}


-keepclassmembers class bais.dynaval.mixin.* {
    @org.spongepowered.asm.mixin.Shadow *;
}

-keepclassmembers class bais.dynaval.mixin.* {
    @org.spongepowered.asm.mixin.Unique *;
}


-keepnames interface * {*;}
-keep interface * extends * {*;}
-keepclassmembers enum * {*;}
```

**Comment by Bais-dynavla** [comment]
@ScottCowe
