### ISSUE TITLE
Optimization info for removed parameters is not updated correctly

### ISSUE THREAD

**Issue by netomi** [Guardsquare/proguard#19]
When optimizing parameters of methods might get removed.

After unused parameters have been removed their corresponding optimization info must be removed as well.

For this purpose the UnusedParameterOptimizationInfoUpdater is used. Unfortunately it uses an AllParameterVisitor to visit all parameters. This one uses internally the descriptor of the method to traverse all parameters. Unfortunately, at this stage, the descriptor is already updated, thus not all parameters are visited.

If a parameter at the end is removed, there is no problem, but if parameters with arbitrary indexes are removed, there are inconsistencies.

The code can not used an AllParameterVisitor, but in fact has to traverse all parameters similar to the ParameterShrinker executed right before it.

**Comment by mrjameshamilton** [comment]
Fixed here: https://github.com/Guardsquare/proguard/commit/2ba28f1a1786a472c373346001f91c61a5711006
