### ISSUE TITLE
Incorrect handling of Record.Signature attribute

### ISSUE THREAD

**Issue by boq** [Guardsquare/proguard#194]
**Summary**
Obfuscating `record` class leaks unobfuscated names and causes loss of class generic data.

**Reproduction steps**
- Run `gradle disassembly` from https://github.com/boq/sandbox/tree/obf-playground
- Compare pre- and post-obfuscation `javap` output in `build/com.example.RecordEntry.txt` and `build/c.txt`
- Notice following differences:
    - `Signature` attribute is missing from class (should be `<K:Ljava/lang/Object;>Ljava/lang/Record;`)
    - `Record[0].Signature` points to unuobfuscated name (should be `La<TK;>;` but is `Lcom/example/Key<TK;>;`)

**Checked versions**
7.1.1, `master` branch, `beta` branch

**Analysis**
- `ClassReferenceInitializer.visitRecordComponentInfo(Clazz clazz, RecordComponentInfo recordComponentInfo)` walks into `Record` attributes using `this` as visitor
- `ClassReferenceInitializer.visitSignatureAttribute(Clazz clazz, SignatureAttribute signatureAttribute)` tries to validate signature as class one (by calling `isValidClassSignature`), not record field one, which fails due to incorrect super class
- That causes `else` branch to run, removing class `Signature`, while leaving `Record[0]` signature unprocessed

Related issue: https://bugs.mojang.com/browse/MC-236947

**Comment by md-5** [comment]
I have opened a pull request that appears to fix both of these issues in your sandbox test case: https://github.com/Guardsquare/proguard-core/pull/28

**Comment by mrjameshamilton** [comment]
> I have opened a pull request that appears to fix both of these issues in your sandbox test case: [Guardsquare/proguard-core#28](https://github.com/Guardsquare/proguard-core/pull/28)

Thanks for the analysis @boq and for the PR @md-5 !
