### ISSUE TITLE
Missing Annotation - Gradle 7

### ISSUE THREAD

**Issue by caseymorris61** [Guardsquare/proguard#205]
I recently updated to Gradle 7, and now I encounter this error when running proguard:
```
  - Type 'ProGuardTask' property 'adaptclassstrings' is missing an input or output annotation.
    ...
  - Type 'ProGuardTask' property 'adaptresourcefilecontents' is missing an input or output annotation.
    ...
  - Type 'ProGuardTask' property 'adaptresourcefilenames' is missing an input or output annotation.
    ...
  - Type 'ProGuardTask' property 'addconfigurationdebugging' is missing an input or output annotation.
    ...
  - Type 'ProGuardTask' property 'allowaccessmodification' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
 
```

### Configuration
```
import proguard.gradle.ProGuardTask

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.guardsquare:proguard-gradle:7.1.1'
    }
}

task proguard(type: ProGuardTask) {
    configuration 'proguard-rules.pro'

    injars 'build/libs/a-inflated.jar'
    outjars 'build/libs/a.jar'
}
```

### Related Issues
#14, #166 

### Versions
I tried various version combinations without success.
Java Version: 1.8.0_191
Proguard: 7.1.0, 7.1.0-beta4, 7.1.1
Gradle: 7.0, 7.3

**Comment by mrjameshamilton** [comment]
Hi @caseymorris61 ! I've tried with Gradle 7.3 and ProGuard 7.1.1 and don't see these errors. Could you share a full project that reproduces the issue?

**Comment by caseymorris61** [comment]
@mrjameshamilton Thank you for the response. In attempts to create a simple repo to demonstrate the error, I discovered my machine had multiple Gradle processes running in the background, and at different versions. I killed all gradle processes via 
```
pkill -f '.*GradleDaemon.*'
./gradlew --stop
```
and this resolved my issue.

Thanks for the support!

**Comment by tjpalmer** [comment]
I'm getting these errors on gradle 7.4.2 and proguard 7.2.2.

**Comment by tjpalmer** [comment]
I discovered the cause in my case. I had an old reference to a different package higher up the classpath that pulled in an old version of proguard, so I wasn't using the correct version.
