### ISSUE TITLE
Kotlin, -keepkotlinmetadata and mangled method names issue

### ISSUE THREAD

**Issue by abelthefirst** [Guardsquare/proguard#208]
Hello!

I've being using ProGuard for the names obfuscation of a Kotlin library that I support. One of the configuration rules there is
```
-keep class kotlin.Metadata { *; }
```
Recently I decided to migrate to the `-keepkotlinmetadata` option, but faced an issue described below (please refer to the https://github.com/abelthefirst/ProGuardFun for a complete demonstrator). So there is an interface:
```Kotlin
interface Service {

    fun useCase(callback: (Int) -> Unit)

    suspend fun useCase(): Result<Int>

}
```
With a following options
```
-keep class kotlin.Metadata { *; }

-keep interface com.example.proguardfun.Service { *; }
```
the public interface after the obfuscation process for the library clients looks like:
```Kotlin
public interface Service {
    public abstract suspend fun useCase(): kotlin.Result<kotlin.Int>

    public abstract fun useCase(callback: (kotlin.Int) -> kotlin.Unit): kotlin.Unit
}
```
, but with the
```
-keepkotlinmetadata

-keep interface com.example.proguardfun.Service { *; }
```
it becomes
```Kotlin
public interface Service {
    public abstract suspend fun `useCase-IoAF18A`(): kotlin.Result<kotlin.Int>

    public abstract fun useCase(p0: (kotlin.Int) -> kotlin.Unit): kotlin.Unit
}
```
(note the mangled name of the suspend function).

Am I misconfiguring something or do not understand the documentation correctly? Or is there an issue on the ProGuard side?

**Comment by mrjameshamilton** [comment]
Hi @abelthefirst ! Thanks for the report. It indeed seems to be an issue with ProGuard, specifically in [ClassReferenceFixer](https://github.com/Guardsquare/proguard-core/blob/master/src/main/java/proguard/classfile/editor/ClassReferenceFixer.java) in ProGuardCORE.

In [ClassReferenceFixer](https://github.com/Guardsquare/proguard-core/blob/master/src/main/java/proguard/classfile/editor/ClassReferenceFixer.java), the names are updated after obfuscation to new names. In this case, the JVM method name is the mangled name, but this name should not be used as the function name in the Kotlin metadata.
