### ISSUE TITLE
How to build proguard "manually"?

### ISSUE THREAD

**Issue by nebukadnezar** [Guardsquare/proguard#209]
I've run into this error when trying to proguard my java application:

   AutocompleteJComboBox$1$1.class] (Unsupported class version number [61.0] (maximum 52.0, Java 1.8)))

presumably this means I need to upgrade proguard - the version I use is still from 2014!

So I git cloned the repo, but then ran into "how to build this thing" problems...

README says "Building ProGuard is easy - you'll just need a Java 8 JDK installed" - except, I have no clue where to even start. There is no build.xml file included anymore for ant by the looks of it?

**Comment by mrjameshamilton** [comment]
Hi @nebukadnezar !

ProGuard uses Gradle as the build system, so you can simply run:

```
./gradlew assemble
```

The artefacts will be generated in the `lib/` folder.

Note that you can download pre-built releases here: https://github.com/Guardsquare/proguard/releases

Java 17 (class file version 61) is supported by ProGuard 7.2.0-beta which you can download from the releases or build yourself.

To build the beta yourself, you'll need to checkout the [beta](https://github.com/Guardsquare/proguard/tree/beta) branch and build with `./gradlew assemble`
