### ISSUE TITLE
ProGuard creating java.lang.VerifyError in kept classes

### ISSUE THREAD

**Issue by EricLangezaal** [Guardsquare/proguard#211]
I am trying to use ProGuard to obfuscate a Java Project (Minecraft plugin). Since I use Maven I used the Maven plugin proguard-maven-plugin, but my issue is related to ProGuard.

I have tried both ProGuard version 7.1.0-beta3 and 7.2.0-beta4 with an identical error.

My project shades in another Java Project it uses as a dependency. I don't want to obfuscate this dependency **at all**, so I used the `keep` arguments to exclude it. However, ProGuard still warned me about "referenced classes" it cannot find for this shaded part. I don't really understand why, since I explicitly told ProGuard not to obfuscate this shaded part. I therefore resorted to telling ProGuard not  to warn me about this shaded part either, which allowed it to run successfully and build my jar. 

My ProGuard configuration:
```
<obfuscate>true</obfuscate>
<options>
    <option>-dontshrink</option>
    <option>-dontoptimize</option>
    <option>-dontnote ** </option>
    <option>-keep public class com.ericdebouwer.regionclaimplus.RegionClaimPlus {}</option>
    <option>-keep public class com.ericdebouwer.regionclaimplus.api.** { public *;}</option>
    <option>-keep public class com.ericdebouwer.regionclaimplus.libs.** {*;}</option> <!-- library to ignore -->
    <option>-dontwarn com.ericdebouwer.regionclaimplus.libs.** </option> <!-- library to ignore -->
</options>
<libs>
    <lib>/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar</lib>
</libs>
```

When putting this jar on a Minecraft Server running Java8 however (Java17 is fine), I get the following error, inside a class which should be ignored by ProGuard:
```
java.lang.VerifyError: Illegal type at constant pool entry 188 in class com.ericdebouwer.regionclaimplus.libs.worldguardwrapper.implementation.v6.WorldGuardImplementation
Exception Details:
  Location:
    com/ericdebouwer/regionclaimplus/libs/worldguardwrapper/implementation/v6/WorldGuardImplementation.registerHandler(Ljava/util/function/Supplier;)V @83: invokevirtual
  Reason:
    Constant pool index 188 is invalid
  Bytecode:
    0x0000000: bb00 1a59 b700 7d4d 2c03 b600 802c 1216
    0x0000010: b600 7f2c b600 7e4e 2d06 bd00 3659 0312
    0x0000020: 1053 5904 120e 5359 0512 3353 b600 9b3a
    0x0000030: 04a7 000f 3a05 bb00 3e59 1905 b700 a3bf
    0x0000040: 2ab4 0059 b600 84bb 0012 592a 2b19 04b7
    0x0000050: 0073 01b6 00bc 57b1                    
  Exception Handler Table:
    bci [19, 49] => handler: 52
  Stackmap Table:
    full_frame(@52,{},{Object[#59]})
    full_frame(@64,{Object[#16],Object[#78],Top,Top,Object[#67]},{})

    at com.ericdebouwer.regionclaimplus.libs.worldguardwrapper.WorldGuardWrapper.<init>(Unknown Source) ~[?:?]
```

Not running ProGuard on my jar makes the error go away. So this means that ProGuard is somehow still doing something to this class resulting in it breaking. I expected that ProGuard would not break a class that it should not obfuscate/touch in the first place. How do I get ProGuard to **properly ignore** a package so it doesn't create Java verification errors?

**Comment by mrjameshamilton** [comment]
Hi @EricLangezaal !

With your configuration, ProGuard won't apply obfuscation to those classes but it will make some changes, for example it will preverify unless you have `-dontpreverify` (preverification is required for the JVM).

The warnings about referenced classes usually mean that you are missing input classes, e.g. library jars.

The error message says `Illegal type at constant pool entry` and you say that it works on Java 17: is it possible that you have used Java 17 features, such as records?

Are you able to share the class before and after ProGuard?

**Comment by EricLangezaal** [comment]
Hi!
Okay that is good to know, so should I use `-dontpreverify` if I want ProGuard to not touch a class at all (given I have excluded it from obfuscation using `-keep`)? 

I know that is what those warnings mean. However the project I am shading is a multi-module project which I am using to avoid having to deal with all those dependencies myself in the first place, so I cannot easily provide them for reference to ProGuard (if I could easily, I wouldn't have to shade in the first place). That is why I am looking for a way to make ProGuard wholly ignore the code in the shaded part, so under `com.ericdebouwer.regionclaimplus.libs.`.

The code doesn't use any Java 17 features. I know this for certain, as the exact same code **without running ProGuard** functions just fine on a Java 8 environment. Only when I make ProGuard obfuscate some parts of my code does it apparently also modify those classes (even though it **shouldn't**) resulting in ProGuard breaking them. 

The class in question is hosted [here](https://github.com/CodeMC/WorldGuardWrapper/blob/e1a10af4017f870318dfe4323cc03fb5b29a1cc3/implementation/v6/src/main/java/org/codemc/worldguardwrapper/implementation/v6/WorldGuardImplementation.java#L158) , I linked the specific function mentioned in the exception. My own jar simply shades and relocates this class (along with the other classes in that GitHub). 

If I open up the compiled Jar again (after ProGuard, even though it didn't obfuscate), that method looks like this:
```
Java
  public void registerHandler(Supplier paramSupplier) {
    Constructor constructor;
    ProxyFactory proxyFactory = new ProxyFactory();
    proxyFactory.setUseCache(false);
    proxyFactory.setSuperclass(ProxyHandler.class);
    try {
      Class clazz = proxyFactory.createClass();
      constructor = clazz.getDeclaredConstructor(new Class[] { WorldGuardImplementation.class, IHandler.class, Session.class });
    } catch (NoSuchMethodException noSuchMethodException) {
      throw new RuntimeException(noSuchMethodException);
    } 
    this.worldGuardPlugin.getSessionManager().registerHandler(new b(this, paramSupplier, constructor), null);
  }
  ```

And what used to be an anonymous Handler is now moved to its own file and is called `b`:
```
Java

class b extends Handler.Factory {
  b(WorldGuardImplementation paramWorldGuardImplementation, Supplier paramSupplier, Constructor paramConstructor) {}
  
  public Handler create(Session paramSession) {
    IHandler iHandler = this.a.get();
    try {
      return this.b.newInstance(new Object[] { this.c, iHandler, paramSession });
    } catch (InstantiationException|IllegalAccessException|java.lang.reflect.InvocationTargetException instantiationException) {
      throw new RuntimeException(instantiationException);
    } 
  }
}
```

_I have temporarily worked around the issue by forking that repository and cutting out that problematic method since I do not use it anyway, but would like to be able to just shade the original repository_

**Comment by mrjameshamilton** [comment]
Thanks for the extra info. 

You must use preverification for running code on a JVM, so `-dontpreverify` isn't a solution for you but it's something where ProGuard could be making a change that you don't expect (because `-keep` rules do not affect it).

You can though try adding `,includecode` to your keep rule to prevent optimization of the code in those classes (see https://www.guardsquare.com/manual/configuration/usage); though I see that you already have `-dontoptimize`.

Can you share the `.class` files before and after ProGuard?

**Comment by EricLangezaal** [comment]
Using `includecode` didn't change anything, I still get the exact same exception if I use 
`<option>-keep, includecode public class com.ericdebouwer.regionclaimplus.libs.** {*;}</option>` for my ProGuard configuration. 

Okay I have uploaded the `.class` files [here](https://ufile.io/f/yyel2). I extracted the ones suffixed with `_BEFORE` from the Proguard Base jar. Since it moved the anonymous function to a separate file here, I attached that one too (I think that should be the right one).

**Comment by mrjameshamilton** [comment]
Hi @EricLangezaal. I had a look at your classes and see the change is related to the changing of a `MethodRef` constant to an `InterfaceMethodRef` constant:

```
// before
        83: invokevirtual #245                // Method com/sk89q/worldguard/session/SessionManager.registerHandler:(Lcom/sk89q/worldguard/session/handler/Handler$Factory;Lcom/sk89q/worldguard/session/handler/Handler$Factory;)Z
// after
        83: invokevirtual #188                // InterfaceMethod com/sk89q/worldguard/session/SessionManager.registerHandler:(Lcom/sk89q/worldguard/session/handler/Handler$Factory;Lcom/sk89q/worldguard/session/handler/Handler$Factory;)Z
```

This matches with the error you showed above:

> java.lang.VerifyError: Illegal type at constant pool entry 188 in class com.ericdebouwer.regionclaimplus.libs.worldguardwrapper.implementation.v6.WorldGuardImplementation

Although it's not clear exactly what part of ProGuard is changing this. I tried processing the class individually but this doesn't reproduce the problem. Are you able to share a full project that reproduces the problem?

**Comment by EricLangezaal** [comment]
Okay, thank you for finding the exact error! I do not know which ProGuard setting is resulting in it doing it. Just for testing purposes, I ran it with the configuration option `-dontobfuscate` (obviously not an option, since I am using ProGuard solely for obfuscation) and it doesn't create this breakage. So apparently it is doing something that messes up this class during its obfuscation, even though it keeps the class.

I cannot easily share a standalone runnable jar, since this entire project is closed source and also runs as an add-on for a Minecraft server (meaning it cannot be run on it's own). However this problematic class (which I shade) is part of [this repository](https://github.com/CodeMC/WorldGuardWrapper/tree/e1a10af4017f870318dfe4323cc03fb5b29a1cc3), which I simply shade. So if you were to shade this project into something/create a jar out of it, I think it will reproduce the issue. If you want I can try see if I can create a jar out of that repository myself and upload that somewhere?

**Comment by mrjameshamilton** [comment]
That would be great if you could create a jar + config that reproduces the problem, then it'll be much easier to figure out what is going on. You can attach it here or email it to me (james dot hamilton at guardsquare dot com)

**Comment by EricLangezaal** [comment]
I made a dummy project with just an empty main class that shades the whole repository I linked earlier. I [uploaded](https://ufile.io/f/72v6y) the proguard base, and the jar after proguard (didn't actually obfuscate a single thing), and the pom.xml. If I put the base jar into my server so it is loaded, it runs just fine. The one that has been through ProGuard (even though all code is **kept**) throws a VerifyError, albeit a slightly different one from before.

**Comment by mrjameshamilton** [comment]
Thanks for creating the sample! Can you also share the new error?

The one that has the error is `ProguardIssue-1.0.jar`?

**Comment by EricLangezaal** [comment]
Yes `ProguardIssue-1.0.jar` gives the following error when loaded (which the base jar does not):
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/ericdebouwer/proguardissue/libs/worldguardwrapper/implementation/v7/WorldGuardImplementation.addRegion(Ljava/lang/String;Ljava/util/List;II)Ljava/util/Optional; @134: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[1]) is not assignable to 'com/sk89q/worldguard/protection/regions/ProtectedRegion'
  Current Frame:
    bci: @134
    flags: { }
    locals: { 'com/ericdebouwer/proguardissue/libs/worldguardwrapper/implementation/v7/WorldGuardImplementation', top, top, top, top, 'java/lang/Object', 'org/bukkit/World', 'java/util/Optional' }
    stack: { 'com/sk89q/worldguard/protection/managers/RegionManager', 'java/lang/Object' }
  Bytecode:
    0000000: 2c03 b900 cf02 00c0 0058 b600 c43a 062c
    0000010: b900 d001 0005 a000 2abb 0036 592b 2c03
    0000020: b900 cf02 00c0 0058 b800 8a2c 04b9 00cf
    0000030: 0200 c000 58b8 008a b700 a33a 05a7 002f
    0000040: 2cb9 00d1 0100 ba00 e900 00b9 00db 0200
    0000050: b800 c2b9 00da 0200 c000 4f3a 07bb 0037
    0000060: 592b 1907 1d15 04b7 00a4 3a05 2a19 06b7
    0000070: 0065 3a07 1907 b600 bd99 001f 1907 b600
    0000080: bcc0 0035 1905 b600 9dbb 0017 5919 0619
    0000090: 05b7 007d b800 bfb0 b800 bab0          
  Stackmap Table:
    append_frame(@64,Top,Object[#90])
    full_frame(@108,{Object[#16],Top,Top,Top,Top,Object[#68],Object[#90]},{})
    full_frame(@152,{},{})

	at com.ericdebouwer.proguardissue.libs.worldguardwrapper.WorldGuardWrapper.<init>(Unknown Source) ~[ProguardIssue-1.0.jar:?]
	at com.ericdebouwer.proguardissue.libs.worldguardwrapper.WorldGuardWrapper.getInstance(Unknown Source) ~[ProguardIssue-1.0.jar:?]
	at com.ericdebouwer.proguardissue.ProGuardIssue.onEnable(Unknown Source) ~[ProguardIssue-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mrjameshamilton** [comment]
It looks like the difference is in the `StackMapTable` which is produced by the preverification process. This needs access to the full class hierarchy to work correctly. For example, in this case ProGuard doesn't know about `com/sk89q/worldguard/protection/regions/ProtectedRegion` so the type is `java/lang/Object` in the processed class:

```
// before
      StackMapTable: number_of_entries = 3
        frame_type = 253 /* append */
          offset_delta = 64
          locals = [ top, class org/bukkit/World ]
        frame_type = 255 /* full_frame */
          offset_delta = 43
          locals = [ class com/ericdebouwer/proguardissue/libs/worldguardwrapper/implementation/v7/WorldGuardImplementation, class java/lang/String, class java/util/List, int, int, class com/sk89q/worldguard/protection/regions/ProtectedRegion, class org/bukkit/World ]
          stack = []
        frame_type = 252 /* append */
          offset_delta = 43
          locals = [ class java/util/Optional ]
```

```
// after
      StackMapTable: number_of_entries = 3
        frame_type = 253 /* append */
          offset_delta = 64
          locals = [ top, class org/bukkit/World ]
        frame_type = 255 /* full_frame */
          offset_delta = 43
          locals = [ class com/ericdebouwer/proguardissue/libs/worldguardwrapper/implementation/v7/WorldGuardImplementation, top, top, top, top, class java/lang/Object, class org/bukkit/World ]
          stack = []
        frame_type = 255 /* full_frame */
          offset_delta = 43
          locals = []
          stack = []
```

This links back to the `-dontwarn` mentioned originally, the class `com/sk89q/worldguard/protection/regions/ProtectedRegion` and other classes should be provided as `libraryjars`.

**Comment by mrjameshamilton** [comment]
Instead of using `-keep` arguments to avoid processing this dependency, you can pass it as a library jar to ProGuard instead. I'm not too familiar with the maven plugin (it's not built/supported by Guardsquare) but can your use-case be supported with the `assembly` / `library` option: https://wvengen.github.io/proguard-maven-plugin/

> Some flagged as library doesn`t need to be processed by ProGuard are added as -libraryjars and added to resulting jar by plugin after ProGuard is finished. For clarity param includeDependency will just add -libraryjars arg to ProGuard and Dependency is not included in resulting jar.

**Comment by EricLangezaal** [comment]
> It looks like the difference is in the `StackMapTable` which is produced by the preverification process. This needs access to the full class hierarchy to work correctly. For example, in this case ProGuard doesn't know about `com/sk89q/worldguard/protection/regions/ProtectedRegion` so the type is `java/lang/Object` in the processed class:
> 
> ```
> // before
>       StackMapTable: number_of_entries = 3
>         frame_type = 253 /* append */
>           offset_delta = 64
>           locals = [ top, class org/bukkit/World ]
>         frame_type = 255 /* full_frame */
>           offset_delta = 43
>           locals = [ class com/ericdebouwer/proguardissue/libs/worldguardwrapper/implementation/v7/WorldGuardImplementation, class java/lang/String, class java/util/List, int, int, class com/sk89q/worldguard/protection/regions/ProtectedRegion, class org/bukkit/World ]
>           stack = []
>         frame_type = 252 /* append */
>           offset_delta = 43
>           locals = [ class java/util/Optional ]
> ```
> 
> ```
> // after
>       StackMapTable: number_of_entries = 3
>         frame_type = 253 /* append */
>           offset_delta = 64
>           locals = [ top, class org/bukkit/World ]
>         frame_type = 255 /* full_frame */
>           offset_delta = 43
>           locals = [ class com/ericdebouwer/proguardissue/libs/worldguardwrapper/implementation/v7/WorldGuardImplementation, top, top, top, top, class java/lang/Object, class org/bukkit/World ]
>           stack = []
>         frame_type = 255 /* full_frame */
>           offset_delta = 43
>           locals = []
>           stack = []
> ```
> 
> This links back to the `-dontwarn` mentioned originally, the class `com/sk89q/worldguard/protection/regions/ProtectedRegion` and other classes should be provided as `libraryjars`.

This does explain the error. I also found out that the maven plugin automatically adds every dependency to ProGuard as `libraryjar`. However, I cannot simply provide all transitive dependencies (used by the shaded part) to ProGuard/in my pom.xml. They are overlapping versions of the same project, and I am shading a multi-module API precisely so I don't have to handle linking all of them myself. So that would defeat the entire purpose of why I am using that shaded API in the first place. 

So that is why I asked my original question, how do I get ProGuard to completely leave a package unmodified, since I cannot provide all dependencies for it nor do I want ProGuard to obfuscate it. I am still surprised ProGuard apparently has no way of properly excluding shaded dependencies, if you want it to obfuscate other parts of a java project. **Just to clarify**: I am actually providing it with all dependencies it needs for code that requires obfuscation, if I don't include the shaded code it works just fine. 


> Instead of using `-keep` arguments to avoid processing this dependency, you can pass it as a library jar to ProGuard instead. I'm not too familiar with the maven plugin (it's not built/supported by Guardsquare) but can your use-case be supported with the `assembly` / `library` option: https://wvengen.github.io/proguard-maven-plugin/
> 
> > Some flagged as library doesn`t need to be processed by ProGuard are added as -libraryjars and added to resulting jar by plugin after ProGuard is finished. For clarity param includeDependency will just add -libraryjars arg to ProGuard and Dependency is not included in resulting jar.
This sounds promising! Does it mean that ProGuard will (correctly) shade it for me, instead of the Maven shade plugin? And do you know if it supports relocation, because I need to move the shaded dependencies?

**Comment by EricLangezaal** [comment]
I "solved" it! Your comment about using ProGuard to shade stuff in made me realise that there is no reason I am shading before applying obfuscation. And by simply reordering my Maven plugins, I can let ProGuard obfuscate my own code first and only after that add the shaded parts, which of course works just fine. I feel so stupid for not realising this earlier, thank you for all the time you spend on this issue anyway!

**Comment by mrjameshamilton** [comment]
Great! Glad that you've solved the issue! :D

**Comment by esskay09** [comment]
@EricLangezaal This was a great solution! You guys are a life saver!
