### ISSUE TITLE
A very fundamental question: how to run proguard?

### ISSUE THREAD

**Issue by mocksu** [Guardsquare/proguard#214]
I have proguard built using "./gradlew assemble", but how to run proguard? "java proguard.ProGuard" couldn't find the java class in the classpath (of course).

I have a jar file which has everything (java classes, data files, external libs) in it, and I just want to obfuscate it.

Thanks for any help!

**Comment by mrjameshamilton** [comment]
Hi @mocksu ! When you build ProGuard the jars will be placed in the lib folder. You can run them with `java -jar lib/proguard.jar`.

The are also scripts in the bin folder to run ProGuard:

```
bin/proguard.sh
```

You can find more information in the manual, starting with the quick start guide https://www.guardsquare.com/manual/quickstart

Note also that if you just want to obfuscate an application you can download ProGuard already built https://github.com/Guardsquare/proguard/releases

If you have any further usage questions you can head over to the [Guardsquare community](https://community.guardsquare.com/) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
