### ISSUE TITLE
How to obfuscate SpringBoot multi-module gradle project without Android Studio

### ISSUE THREAD

**Issue by shuishuijiao** [Guardsquare/proguard#216]
I don't see any hint in the manual about multi-modle gradle project without Android Studio. 
Can you give me a model or hint?
3QS very much.

**Comment by mrjameshamilton** [comment]
Hi @shuishuijiao !

The example [here](https://github.com/Guardsquare/proguard/tree/master/examples/spring-boot) shows how to setup a Gradle Spring Boot project with ProGuard, hopefully that should help you.

If you have further usage questions, you can also head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get help with your configuration from our team of engineers and skilled community members.
