### ISSUE TITLE
After obfuscation constructor removed from the class

### ISSUE THREAD

**Issue by ypkkhatri** [Guardsquare/proguard#233]
I have recently started looking into this plugin, but I see some of the classes constructor are missing from the class and in the map file it says:
```
void <init>(...) -> <init>
```
Where three dots are the constructor arguments.

For example:
```java
class MyClass {
    public MyClass(MyBase s) {}
}
```
Map files show:
```
MyClass -> a
   void <init>(MyBase) -> <init>
```

Converted class
```java
class a {
     // No constructor
}
```

Am I missing something, because it happening to a lot of classes?

**Comment by ypkkhatri** [comment]
Does anyone help me with the issue?

**Comment by mrjameshamilton** [comment]
Hi @ypkkhatri ! For a usage question like this, please head over to the [Guardsquare community](https://community.guardsquare.com/) where you can get tips and advice on your configuration from our team of engineers and skilled community members.

Some tips already:

* `void <init>(...) -> <init>`: the mapping file does not show the parameters on the right hand-side of the `->`
* The parameters and constructors may be removed if they are unused by the shrinking/optimization phases -> you can narrow this down by disabling these to see which (-dontshrink, -dontoptimize)
* You can add keep rules to keep constructors, if necessary e.g. `-keep class * { <init>(...); }`
* You can use the ProGuard Playground to help visualise the effects of keep rules: https://playground.proguard.com/

**Comment by ypkkhatri** [comment]
> Hi @ypkkhatri ! For a usage question like this, please head over to the [Guardsquare community](https://community.guardsquare.com/) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
> 
> Some tips already:
> 
> * `void <init>(...) -> <init>`: the mapping file does not show the parameters on the right hand-side of the `->`
> * The parameters and constructors may be removed if they are unused by the shrinking/optimization phases -> you can narrow this down by disabling these to see which (-dontshrink, -dontoptimize)
> * You can add keep rules to keep constructors, if necessary e.g. `-keep class * { <init>(...); }`
> * You can use the ProGuard Playground to help visualise the effects of keep rules: https://playground.proguard.com/

Thanks for the tips, this is my first-time use of proguard, I will follow the community.
