### ISSUE TITLE
ProGuardGUI console does not show console warnings

### ISSUE THREAD

**Issue by mrjameshamilton** [Guardsquare/proguard#239]
This is due to the switch to Log4j for logging, the output is no longer captured and shown in the GUI text area.

![image](https://user-images.githubusercontent.com/6151131/161039090-2c4807f7-3dbe-4666-8575-de3411070091.png)

The warnings should still be visible in the console when starting the GUI from the command line.

**Comment by TWiStErRob** [comment]
Until this is properly fixed, would it make sense to add a label on top of the log saying it is in the command line window?
