### ISSUE TITLE
JDK 19 support

### ISSUE THREAD

**Issue by boris-petrov** [Guardsquare/proguard#247]
JDK 19 is going to land in September and most likely project Loom be [previewed](https://openjdk.java.net/jeps/425) there. I am eagerly awaiting it but I'm unsure as to what that means for ProGuard. Will ProGuard have to do any changes to support that?

**Comment by boris-petrov** [comment]
@mrjameshamilton thanks for the information! That's great news! If you think there are/might be changes in JDK 19 that will require support in ProGuard, you can use this issue for that. If not, you can close it. :) Thanks!

**Comment by dougxc** [comment]
I've tested proguard on JDK 19 with this patch applied to [VersionConstants.java](https://github.com/Guardsquare/proguard-core/blob/master/base/src/main/java/proguard/classfile/VersionConstants.java):
```
diff --git a/base/src/main/java/proguard/classfile/VersionConstants.java b/base/src/main/java/proguard/classfile/VersionConstants.java
index 7fad5ea..adb1a98 100644
--- a/base/src/main/java/proguard/classfile/VersionConstants.java
+++ b/base/src/main/java/proguard/classfile/VersionConstants.java
@@ -62,6 +62,8 @@ public class VersionConstants
     public static final int CLASS_VERSION_17_MINOR  = 0;
     public static final int CLASS_VERSION_18_MAJOR  = 62;
     public static final int CLASS_VERSION_18_MINOR  = 65535;
+    public static final int CLASS_VERSION_19_MAJOR  = 63;
+    public static final int CLASS_VERSION_19_MINOR  = 65535;
 
     public static final int CLASS_VERSION_1_0 = (CLASS_VERSION_1_0_MAJOR << 16) | CLASS_VERSION_1_0_MINOR;
     public static final int CLASS_VERSION_1_2 = (CLASS_VERSION_1_2_MAJOR << 16) | CLASS_VERSION_1_2_MINOR;
@@ -81,6 +83,7 @@ public class VersionConstants
     public static final int CLASS_VERSION_16  = (CLASS_VERSION_16_MAJOR  << 16) | CLASS_VERSION_16_MINOR;
     public static final int CLASS_VERSION_17  = (CLASS_VERSION_17_MAJOR  << 16) | CLASS_VERSION_17_MINOR;
     public static final int CLASS_VERSION_18  = (CLASS_VERSION_18_MAJOR  << 16) | CLASS_VERSION_18_MINOR;
+    public static final int CLASS_VERSION_19  = (CLASS_VERSION_19_MAJOR  << 16) | CLASS_VERSION_19_MINOR;
 
-    public static final int MAX_SUPPORTED_VERSION = CLASS_VERSION_18;
+    public static final int MAX_SUPPORTED_VERSION = CLASS_VERSION_19;
 }
```
It would be great to have a (beta) release with this patch such that I can use it in our CI system.

**Comment by mrjameshamilton** [comment]
Hi @dougxc ! I've made the update in [ProGuardCORE](https://github.com/Guardsquare/proguard-core/commit/ea784c9d4324783f30c40cb365e25a4027184f8d), hoping to get a ProGuard version out soon.

**Comment by dougxc** [comment]
Hi @mrjameshamilton I see that ProGuardCORE 9.0.3 is now on [maven](https://search.maven.org/artifact/com.guardsquare/proguard-core/9.0.3/jar).
Do you have a rough ETA as to when there will be proguard-base and proguard-retrace jars on maven that use proguard-core 9.0.3?
I am currently modifying the classpath to use `7.2.0-beta1` of these jars with proguard-core 9.0.3. It seems to work but having jars designed to work together would be more reassuring.

**Comment by mrjameshamilton** [comment]
Hi @dougxc ! Sorry for the delay! We've release 7.3.0-beta1 :)

**Comment by dougxc** [comment]
Thanks! I assume it will show up on maven before too long?

**Comment by mrjameshamilton** [comment]
> Thanks! I assume it will show up on maven before too long?

Yes, should be there soon!
