### ISSUE TITLE
GUI: "Please correct the above warnings first."

### ISSUE THREAD

**Issue by TWiStErRob** [Guardsquare/proguard#249]
![image](https://user-images.githubusercontent.com/2906988/166718720-4aa22af7-0641-4376-aa54-008a180f48dc.png)

no idea what to do... other than report a bug to get a change, to get more info.

**Comment by mrjameshamilton** [comment]
Hi @TWiStErRob ! 

Thanks for the report. This is a known issue (https://github.com/Guardsquare/proguard/issues/239). If you start the GUI from the command line you should see the missing warnings in the console.
