### ISSUE TITLE
keep rule for Kotlin companion not working with `-keepkotlinmetadata`

### ISSUE THREAD

**Issue by trychen** [Guardsquare/proguard#252]
While I'm using `-keepclassmembers` to keep the name of `companion object` in Kotlin with `-keepkotlinmetadata`, the companion will still being obfuscated. And the rule works without `-keepkotlinmetadata`. 

ProGuard Rules:
```
-keepkotlinmetadata

-keepclassmembers class ** {
    *** Companion;
}
```

Kotlin Class:
```
class Hello {
    companion object {
        fun test() {
            println("Hello, world!")
        }
    }
}
```

mapping:
```
com.test.Hello -> com.test.a:
    com.test.Hello$Companion Companion -> a        # <--- HERE 
    void <clinit>() -> <clinit>
com.test.Hello$Companion -> com.test.a$a:
    void <init>() -> <init>
    void test() -> a
    void <init>(kotlin.jvm.internal.DefaultConstructorMarker) -> <init>
```

**Comment by mrjameshamilton** [comment]
Hi @trychen ! I assume you solved your issue? For future reference, the [ProGuard Playground](https://playground.proguard.com/) would be useful for a question like this - you can upload a sample and interactively try out keep rules, visualising their effects.

You can also head over to the [Guardsquare community](https://community.guardsquare.com/) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
