### ISSUE TITLE
Question about changing the methods body during obfuscation, by the classes explicitly marked to be kept 

### ISSUE THREAD

**Issue by devprojectsme** [Guardsquare/proguard#253]
Hello,

not sure this is an issue, or rather an understanding question. 

Problem:
Have a quarkus based microservice. During the packaging quarkus dies generate some code in classes under `io.quarkus.runtime.generated` .
The obfuscation config contains the instructions to keep all of the quarkus related  classes and interfaces:
`-keep class io.quarkus.** { *; }  
-keep class io.smallrye.** { *; }  
-keep class io.vertx.** { *; }  
-keep class io.netty.** { *; }  
-keepclassmembers public enum * { *; }  
...
-keep interface io.quarkus.** { *; }  
-keep interface io.smallrye.** { *; }  
-keep interface io.vertx.** { *; }  
-keep interface io.netty.** { *; }`

BUT
the obfuscation step changes the content of the generated classes(see [here](https://github.com/quarkusio/quarkus/issues/25602#issuecomment-1141383102)).

I assume this has something to do with the obfuscator attempt to fix the namings (like it is done [here](https://github.com/Guardsquare/proguard/blob/master/base/src/main/java/proguard/obfuscate/Obfuscator.java#L607)).

But as I am not specializing on the internal logic of the Proguard, I was going to ask if someone could explain me, how to avoid changing the  generated methods in the classes that have been marks for keeping.

Thanks in advance!

**Comment by mrjameshamilton** [comment]
Hi @devprojectsme !

If I understand correctly, the method is not obfuscated when it should be?

It's possible that the `refefencedMethod` is not set, which can happen if the full class hierarchy is not available when obfuscating. 

Do you get warnings in the log about missing classes?

**Comment by devprojectsme** [comment]
Hi @mrjameshamilton 

thanks for your reply! 

Actually it is the other way around. :)
I use Quarkus as the new base framework for the microservice(s). To speed things up it generates some synthetic code during buildtime. That code then allows faster startup at runtime. 
So even though I have set the Proguard settings to keep all of the Quarkus classes and interfaces (generated and included from the lib), I see an unexpected behavior, that the implementation of some of the methods in the generated classes(have not checked the other ones) does change. 

To your question :

> Do you get warnings in the log about missing classes?

Yes, I do. Here the Log excerpt to it:

<details><summary>LOG-Exceprt</summary><blockquote>
 [proguard] Note: there were 1 unkept descriptor classes in kept class members.
 [proguard]       You should consider explicitly keeping the mentioned classes
 [proguard]       (using '-keep').
 [proguard]       (https://www.guardsquare.com/proguard/manual/troubleshooting#descriptorclass)
 [proguard] Note: there were 163 library classes explicitly being kept.
 [proguard]       You don't need to keep library classes; they are already left unchanged.
 [proguard]       (https://www.guardsquare.com/proguard/manual/troubleshooting#libraryclass)
 [proguard] Warning: there were 1 unresolved references to classes or interfaces.
 [proguard]          You may need to add missing library jars or update their versions.
 [proguard]          If your code works fine without the missing classes, you can suppress
 [proguard]          the warnings with '-dontwarn' options.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedclass)
 [proguard] Warning: there were 5 instances of library classes depending on program classes.
 [proguard]          You must avoid such dependencies, since the program classes will
 [proguard]          be processed, while the library classes will remain unchanged.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#dependency)
 [proguard] Warning: there were 1 unresolved references to program class members.
 [proguard]          Your input classes appear to be inconsistent.
 [proguard]          You may need to recompile the code.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedprogramclassmember)
 [proguard] Warning: there were 21 unresolved references to library class members.
 [proguard]          You probably need to update the library versions.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedlibraryclassmember)
 [proguard] Note: you're ignoring all warnings!
  </blockquote></details>

**Comment by devprojectsme** [comment]
After a few days of trials it is still hard to tell which one of many visitors within the Proguard processing exactly changes the method code. Hence, we have decided to use the native image and not the obfuscation path. Closing this ticket.
