### ISSUE TITLE
ERROR: Plugin with id 'proguard' not found.

### ISSUE THREAD

**Issue by kevin-rabefaritra** [Guardsquare/proguard#26]
I've initially tried to run a locally stored Proguard version and have followed the guidelines as mentioned [in the manual](https://www.guardsquare.com/en/products/proguard/manual/gradleplugin).

In my project `build.gradle`:

`buildscript {
repositories {
flatDir dirs: '<PATH_TO_PROGUARD_LOCAL_LIB_DIR>'
...
}
dependencies {
        ...
        classpath 'com.android.tools.build:gradle:GRADLE_VERSION'
        classpath ':proguard:'
        ...
    }
}`

And in my module `build.gradle`:

`apply plugin: 'com.android.application'
apply plugin: 'proguard'`

However, when running the Gradle project sync, I ran into the following error:
`ERROR: Plugin with id 'proguard' not found.`

First, I thought it was due to some configurations within my project but I've tried the default project included in the source at `proguard/examples/android-plugin` and still got the same error.

**Comment by rekire** [comment]
In your `<project root>/build.gradle` is in the block buildscript/dependencies this line missing:

    classpath 'net.sf.proguard:proguard-gradle:6.2.2'

**Comment by kevin-rabefaritra** [comment]
**Update** :

Turns out `apply plugin: 'proguard'` inside the module's `build.gradle` is not necessary.
Only the project `build.gradle` needs to be modified as the following :

`{`
`repositories {   `     
`flatDir dirs: '${PATH_TO_LOCAL_PROGUARD_LIB}'`
 `   google()           `
  `  jcenter()`
   `     }`
    `    dependencies {`
`...`
  `          classpath ':proguard:'`
    `    }`
   ` }`

The [manual](https://www.guardsquare.com/en/products/proguard/manual/gradleplugin) shows those two lines at the end of the file: 

`apply plugin: 'com.android.application'`
`apply plugin: 'proguard'`

but they're not necessary, only `apply plugin: 'com.android.application'` is needed in the app `build.gradle`.
