### ISSUE TITLE
Proguard breaks generics of map fields

### ISSUE THREAD

**Issue by Obliviated** [Guardsquare/proguard#260]
I just want to obfuscate names of classes and members. But ProGuard breaks my code. My project works perfectly while i don't obfuscate it.

## Decompiled original class (no obfuscate)
![image](https://user-images.githubusercontent.com/36128276/176023232-f7f2fb6e-7e88-44fa-91e6-f2c28837f360.png)

## Decompiled obfuscated class
![image](https://user-images.githubusercontent.com/36128276/176023345-c4ad1c4c-2935-4efb-85dc-7bc8e66a15e4.png)

If i am not in a missunderstanding. ProGuard does not change types of the fields. My project prints error when i try obfuscated jar and i blame ProGuard rightnow.

My ProGuard config: https://pastebin.pl/view/e3ce639a

**Comment by rubenpieters** [comment]
Can you try adding `-keepattributes Signature` to your configuration? This will instruct ProGuard to keep the signature attributes in the bytecode.

**Comment by Obliviated** [comment]
> Can you try adding `-keepattributes Signature` to your configuration? This will instruct ProGuard to keep the signature attributes in the bytecode.
it works! thank you.
