### ISSUE TITLE
Peephole optimizer can produce strings constants that are too large

### ISSUE THREAD

**Issue by mrjameshamilton** [Guardsquare/proguard#267]
Processing the Now in Android app with 5 optimization passes results in the following error:

```
> Unexpected error while writing class [com/google/samples/apps/nowinandroid/core/network/fake/FakeDataSource] (Overflow of unsigned short value [144603])
```

The `FakeDataSource` class contains a huge string in the source; ProGuard's peep hole optimization concatenates the StringBuilder append parameters into a single string resulting in a string that's too large for the constant pool Utf8 constant entry.

# Workaround

Disable optimization for the class or disable string optimizations

```
-keep,includecode,allowobfuscation,allowshrinking class com.google.samples.apps.nowinandroid.core.network.fake.FakeDataSource

// or

-optimizations !code/simplification/string
```

**Comment by piazzesiNiccolo-GS** [comment]
Resolved by bacde1cedeff76988fa70450e74a353476591c09
