### ISSUE TITLE
ProGuard not working on Windows

### ISSUE THREAD

**Issue by simonschiller** [Guardsquare/proguard#272]
I've recently tried running ProGuard on a Windows machine (see [here](https://github.com/spotify/ruler/runs/7863488891)), but it failed with the following error:
```
Android resource linking failed
error: failed to open 'D:\a\ruler\ruler\sample\proguard\build/intermediates/proguard/configs/aapt_rules.pro': The system cannot find the file specified. (2).
```

Looks like the path to the generated AAPT rules is always using Unix-style path separators and therefore fails on Windows (see [here](https://github.com/Guardsquare/proguard/blob/master/gradle-plugin/src/main/kotlin/proguard/gradle/plugin/android/AndroidPlugin.kt#L113) and potentially [here](https://github.com/Guardsquare/proguard/blob/master/gradle-plugin/src/main/kotlin/proguard/gradle/plugin/android/tasks/PrepareProguardConfigDirectoryTask.kt#L11)).

**Comment by mrjameshamilton** [comment]
Closed by #277
