### ISSUE TITLE
Is there any way to skip some classes or jars and just copy to the next transform?

### ISSUE THREAD

**Issue by zjiecode** [Guardsquare/proguard#289]
First of all, I would like to thank ProGuard, which has helped me a lot.

However, ProGuard spends a lot of time in my project build, which causes my project build to be very slow. There are many classes and jars in my project that do not need to be processed by ProGuard.

Is there any way I can let ProGuard skip processing these classes or jars to save build time，For example,just copy to the next transform?

Thank you.

**Comment by mrjameshamilton** [comment]
Hi @zjiecode !

Thanks for your enthusiasm for ProGuard!

Depending on your exact use-case, the answer can vary. Some pointers that might help:

* you can filter the input to ProGuard; see the examples here https://www.guardsquare.com/manual/configuration/examples#filtering
* `-libraryjars` are not processed by ProGuard, maybe you can pass some parts of your app as library jars instead

This issue tracker here is intended for tracking bugs. Please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.

**Comment by zjiecode** [comment]
Thanks you, I'm sorry, I didn't make it clear.

I use ProGuard in gradle, use it make Android application project. 
My Android application dependent many jars，such as : `A.jar`,`B.jar` and `C.jar`, I want `A.jar `use Proguard deal normaly, but `B.jar` and `C.jar` don't processed by Proguard,just copy it to next transform(next Android build transform). **A.jar,B.jar and C.jar are all dependent at runtime,I need them normal output.**

I want to Proguard skip optimize B.jar and C.jar to save build time, My proguard version is  7.2.3.

ProGuard can impl this function?could you give me some suggestions?

Thanks you very much.
