### ISSUE TITLE
Logging statements should be supressable

### ISSUE THREAD

**Issue by paplorinc** [Guardsquare/proguard#29]
We're using ProGuard for obfuscation only and we're getting a lot of output during build that we would like to be able to silence on demand.

Examples of info output that we would like to be able to mute:
* `Reading library jmod`
* `Reading library jar`
* `Reading program jar`
* `Reading program directory` 
* `Preparing output jar`
* `Copying resources from program jar`

And a few warnings that we want to keep for now:
* `Note: duplicate definition of library class`

The sources indicate that [`System.out.println`](https://github.com/Guardsquare/proguard/blob/679425e5d87834e3f7cd1cbe09f120a410c67a66/base/src/proguard/DataEntryReaderFactory.java#L88) is used currently for displaying these - which are cumbersome to quiet down.
Would it be possible to use SLF4J for the library's logging needs - preferably separating info and warning level logs, as described above.

**Comment by paplorinc** [comment]
Any progress here, @dzan? Our logs are still spammed by the `S.o.println` entries.

**Comment by britter** [comment]
Hey friends, any feedback about this? Is this something you would consider including into Proguard? If there are chances that something like this gets included we might spend some time working on a PR.

**Comment by EricLafortune** [comment]
It's on our list, but other things have a higher priority. We're open to PRs. We try to avoid adding unnecessary external dependencies, so java.util.logging may do.

**Comment by britter** [comment]
@EricLafortune thanks for the feedback. We'll see what we can do.
