### ISSUE TITLE
Do you support javafx application with FXML

### ISSUE THREAD

**Issue by garawaa** [Guardsquare/proguard#292]
I tried this tool to obfuscate my javafx application with fxml. But it gives error messeges. Please give me some tips for fxml java applications?

**Comment by mrjameshamilton** [comment]
Hi @garawaa !

JavaFX applications should be supported. However, this issue tracker here is intended for tracking bugs. Please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.
