### ISSUE TITLE
question about array index limit

### ISSUE THREAD

**Issue by ihsinme** [Guardsquare/proguard#297]
sorry if my question is stupid.
shouldn't the index limit be strictly less than the size.

https://github.com/Guardsquare/proguard/blob/84ac82eb516d08a53e5a2511ff67188279344790/base/src/main/java/proguard/fixer/kotlin/KotlinAnnotationCounter.java#L75

**Comment by JagoGyselinck** [comment]
Hello @ihsinme 

It's definitely not a stupid question, this is indeed a bug in the code :-) 
Assigning to @TimvdBroecke

**Comment by tvoc-gs** [comment]
Hello @ihsinme,

This has been fixed with 745a681b3248de74b028a1d3ea9a14b46dc1437d and will be included with the next release.
