### ISSUE TITLE
Infinite optimize loop if optimizationpasses was set to 10000

### ISSUE THREAD

**Issue by Klayflash** [Guardsquare/proguard#3]
Version: proguard6.1.1
[javaSandbox.zip](https://github.com/Guardsquare/proguard/files/3472464/javaSandbox.zip)

This example provides infinite loop.

Infinite out:

> Shrinking...
> Removing unused program classes and class elements...
>   Original number of program classes: 2
>   Final number of program classes:    2
> Optimizing (**pass 221**/10000)...
>   Number of finalized classes:                   0
>   Number of unboxed enum classes:                0
>   Number of vertically merged classes:           0
>   Number of horizontally merged classes:         0
>   Number of merged wrapper classes:              0
>   Number of removed write-only fields:           1
>   Number of privatized fields:                   0
>   Number of inlined constant fields:             0
>   Number of privatized methods:                  0
>   Number of staticized methods:                  0
>   Number of finalized methods:                   0
>   Number of desynchronized methods:              0
>   Number of simplified method signatures:        0
>   Number of removed method parameters:           0
>   Number of inlined constant parameters:         0
>   Number of inlined constant return values:      0
>   Number of inlined short method calls:          0
>   Number of inlined unique method calls:         0
>   Number of inlined tail recursion calls:        0
>   Number of merged code blocks:                  0
>   Number of variable peephole optimizations:     0
>   Number of arithmetic peephole optimizations:   0
>   Number of cast peephole optimizations:         0
>   Number of field peephole optimizations:        0
>   Number of branch peephole optimizations:       0
>   Number of object peephole optimizations:       0
>   Number of string peephole optimizations:       0
>   Number of math peephole optimizations:         0
>   Number of simplified instructions:             0
>   Number of removed instructions:                0
>   Number of removed local variables:             0
>   Number of removed exception blocks:            0
>   Number of optimized local variable frames:     0

**Comment by netomi** [comment]
Problem is related to issue #4, write only fields are not removed although counted as performed optimization, thus the optimizer does not stop.

**Comment by netomi** [comment]
ProGuard 6.2.0 has been released including a fix for this issue.
