### ISSUE TITLE
Using Proguard's gradle plugin without Android target

### ISSUE THREAD

**Issue by rekire** [Guardsquare/proguard#30]
I want to use proguard to minify a fat jar more or less as you do it for Android, byside my target is not Android.

I get a crash when applying the plugin in [ProGuardPlugin.groovy line 47](https://github.com/Guardsquare/proguard/blob/f4d94ae21e9379010f5e4d4316fdb7f041a8b705/gradle/src/proguard/gradle/ProGuardPlugin.groovy)  with a `NoClassDefFoundError`, because you are throwing a `BadPluginException` when the Android plugin was not detected (which is itself part of the Android Plugin).

Could you extend your plugin to remove the hard dependency on the Android plugin?

**Comment by rekire** [comment]
I created a simple gradle task which does its job for me:

```
task proguard() {
    doLast {
        proguard.Configuration configuration = new proguard.Configuration();
        // Parse the options specified in the command line arguments.
        String[] args = ["-injar",
                         "${project.buildDir}/libs/fatjar.jar",
                         "-outjar",
                         "${project.buildDir}/libs/optimized.jar",
                         "-libraryjars",
                         "${System.properties["java.home"]}/lib/rt.jar",
                         "@${project.projectDir}/src/main/minify.pro"];
        def parser = new proguard.ConfigurationParser(args, System.getProperties())
        try {
            parser.parse(configuration);
        }
        finally {
            parser.close();
        }

        // Execute ProGuard with these options.
        new proguard.ProGuard(configuration).execute();
    }
}
proguard.dependsOn("fatJar")
```

The only two dependencies are to add the dependency `classpath 'net.sf.proguard:proguard-base:6.2.2'` and to define a "minified.pro" file holding the rules for your project.

**Comment by 12345mnb** [comment]
我看不懂

rekire <notifications@github.com> 於 2020年2月25日 週二 下午8:35 寫道：

**Comment by 12345mnb** [comment]
--
傳送自 Android 版 
-------- 已轉寄的郵件 --------
寄件者： GitHub  noreply@github.com
收件人： 12345mnb  a0961113853@gmail.com
日期： 星期四, 05 3月 2020, 08:47上午 +08:00
主旨： [GitHub] Please verify your device

>Hey 12345mnb!
>
>A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.
>
>Device: Chrome on Android
>Verification code: 444506
>
>If you did not attempt to sign in to your account, your password may be compromised. Visit  https://github.com/settings/admin to create a new, strong password for your GitHub account.
>
>If you'd like to automatically verify devices in the future, consider enabling two-factor authentication on your account. Visit  https://help.github.com/articles/configuring-two-factor-authentication learn about two-factor authentication.
>
>If you decide to enable two-factor authentication, ensure you retain access to one or more account recovery methods. See  https://help.github.com/articles/configuring-two-factor-authentication-recovery-methods in the GitHub Help.
>
>Thanks,
>The GitHub Team

﻿file:///storage/sdcard1/data/system/big_data_usage_call_gesture.txt
https://cdn.f5.com/product/apm/apps/eula.html

**Comment by 12345mnb** [comment]
--
傳送自 Android 版
-------- 已轉寄的郵件 --------
寄件者： GitHub  noreply@github.com
收件人： 12345mnb  a0961113853@gmail.com
日期： 星期四, 05 3月 2020, 09:52上午 +08:00
主旨： [GitHub] Please verify your device

>Hey 12345mnb!
>
>A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.
>
>Device: Chrome on Android
>Verification code: 645956
>
>If you did not attempt to sign in to your account, your password may be compromised. Visit  https://github.com/settings/admin to create a new, strong password for your GitHub account.
>
>If you'd like to automatically verify devices in the future, consider enabling two-factor authentication on your account. Visit  https://help.github.com/articles/configuring-two-factor-authentication learn about two-factor authentication.
>
>If you decide to enable two-factor authentication, ensure you retain access to one or more account recovery methods. See  https://help.github.com/articles/configuring-two-factor-authentication-recovery-methods in the GitHub Help.
>
>Thanks,
>The GitHub Team

**Comment by 12345mnb** [comment]
--
傳送自 Android 版 myMail -------- 已轉寄的郵件 --------
寄件者： GitHub  noreply@github.com
收件人： 12345mnb  a0961113853@gmail.com
日期： 星期四, 05 3月 2020, 09:55上午 +08:00
主旨： [GitHub] Please verify your device

>Hey 12345mnb!
>
>A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.
>
>Device: Chrome on Android
>Verification code: 206153
>
>If you did not attempt to sign in to your account, your password may be compromised. Visit  https://github.com/settings/admin to create a new, strong password for your GitHub account.
>
>If you'd like to automatically verify devices in the future, consider enabling two-factor authentication on your account. Visit  https://help.github.com/articles/configuring-two-factor-authentication learn about two-factor authentication.
>
>If you decide to enable two-factor authentication, ensure you retain access to one or more account recovery methods. See  https://help.github.com/articles/configuring-two-factor-authentication-recovery-methods in the GitHub Help.
>
>Thanks,
>The GitHub Team

**Comment by 12345mnb** [comment]
--
傳送自 Android  -------- 已轉寄的郵件 --------
寄件者： GitHub  noreply@github.com
收件人： 12345mnb  a0961113853@gmail.com
日期： 星期四, 05 3月 2020, 08:47上午 +08:00
主旨： [GitHub] Please verify your device

>Hey 12345mnb!
>
>A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.
>
>Device: Chrome on Android
>Verification code: 444506
>
>If you did not attempt to sign in to your account, your password may be compromised. Visit  https://github.com/settings/admin to create a new, strong password for your GitHub account.
>
>If you'd like to automatically verify devices in the future, consider enabling two-factor authentication on your account. Visit  https://help.github.com/articles/configuring-two-factor-authentication learn about two-factor authentication.
>
>If you decide to enable two-factor authentication, ensure you retain access to one or more account recovery methods. See  https://help.github.com/articles/configuring-two-factor-authentication-recovery-methods in the GitHub Help.
>
>Thanks,
>The GitHub Team

**Comment by 12345mnb** [comment]
--
傳送自 Android 版 myMail -------- 已轉寄的郵件 --------
寄件者：  a0961113853@gmail.com
收件人：  a0961113853@gmail.com
日期： 星期五, 06 3月 2020, 05:21下午 +08:00
主旨： 給自己發郵件

>--
>傳送自 Android 版 myMail

**Comment by rekire** [comment]
What are you trying to tell me? It looks like spam what you are doing

**Comment by 12345mnb** [comment]
<a0961113853@gmail.com> 于 2020年3月6日周五 17:41写道：

> --
> 傳送自 Android 版 myMail
> -------- 已轉寄的郵件 --------
> 寄件者： a0961113853@gmail.com
> 收件人： a0961113853@gmail.com
> 日期： 星期五, 06 3月 2020, 05:21下午 +08:00
> 主旨： 給自己發郵件
>
> --
> 傳送自 Android 版 myMail
>
>

**Comment by DavidSanf0rd** [comment]
Hi man, any news on this one. I'm trying to use Gradle's plugin in a jar file completely unrelated to Android.

**Comment by rekire** [comment]
Try that gradle task above that works for me

**Comment by joffrey-bion** [comment]
Hey I'm also looking forward to this!
Btw it looks like Proguard's docs could also be more friendly to non-android projects.

@rekire using proguard 6.2.2, couldn't you use directly the plugin's task?
In [this other issue](https://github.com/Guardsquare/proguard/issues/66), it seems implied that the dependency on Android arrived in version 7.0.0 only.

**Comment by mrjameshamilton** [comment]
For non-Android apps, instead of the plugin you can use the Gradle task https://www.guardsquare.com/en/products/proguard/manual/gradle

There is still a problem with the extra dependency on the android build tools that we plan to solve.

Thanks for the feedback regarding the documentation @joffrey-bion we'll take that into account!

**Comment by joffrey-bion** [comment]
@mrjameshamilton thanks a lot for taking the feedback.

Yes, I had finally figured out that basically the proguard plugin is only for android, and that non-android projects should just define a custom task using the proguard task type. I don't believe this is quite clear in the docs.

For instance, in the "Gradle task" section that you linked, it reads:

> ProGuard can be run as a task in the Java-based build tool Gradle (version 2.1 or higher).

This doesn't suggest that for non-android projects, proguard *cannot be applied* as a Gradle plugin, and a custom task *has to be* created manually. It would be great to mention that there.

Also on the other hand in the plugin section, maybe you could mention that it's only valid for android projects. My first reaction was that the docs were too focused on android and didn't explain how the plugin should be used for non-android projects, but the truth is that the plugin itself is just not meant for non-android project, and *cannot* be used in that case.
The first sentence suggests it, but it's hard to tell whether the android integration is a capability or a dependency.

**Comment by mrjameshamilton** [comment]
Thanks for the detailed reply! I agree with your points, we'll see what we can do to improve the manual with regards to the differences currently between the plugin and task. Indeed the focus in the manual has been Android since the majority of ProGuard users in recent years have been Android developers (since it is/was part of the Android build chain). But we should definitely improve the docs for non-Android users!

We're also thinking about how we can improve the Gradle integration since there are currently multiple problems with it.

I've now [removed the compile dependency](https://github.com/Guardsquare/proguard/commit/c1f4ce0553b135e8541067232d909bc1b41f814d) on the Android build tools and improved the error message when trying to use the plugin in a non-Android project, so at least it should be more obvious.

**Comment by joffrey-bion** [comment]
Awesome, thanks a lot for these improvements!

**Comment by ArcticLampyrid** [comment]
Any new releases?

**Comment by mrjameshamilton** [comment]
Hi @ArcticLampyrid ! No release yet, but the hard dependency on Android fix is already on master and you could build yourself: https://github.com/Guardsquare/proguard#-building-proguard
