### ISSUE TITLE
Support the -target for Java versions after Java 11 for upgrading class versions.

### ISSUE THREAD

**Issue by 0-x-2-2** [Guardsquare/proguard#301]
Before Java 11 we used this flag to upgrade Java 1.5/1.6/1.7 class files to Java 1.8 which no longer is possible if you have any classes after Java 11 even if you set the target to the highest Java class version used.

**Comment by mrjameshamilton** [comment]
Hi @0-x-2-2 ! 

The reason that `-target` is deprecated is that backporting to old versions is no longer practically with the 6 monthly Java release schedule introduction new features. The backporting was useful for Android integration when it older Android versions did not support new Java features.

What is your use-case for upgrading the Java class versions?

**Comment by 0-x-2-2** [comment]
It is understandable that backporting isn't feasible, thankfully we haven't used that feature for years so it doesn't really matter to us. We currently are upgrading, shrinking, and obfuscating old class files from Java 1.5-1.7 to Java 1.8 with ProGuard.

Proper stack frames and Java 1.8+ class version features being accessible are required due to the runtime transformation of our application from programs that don't know how to handle such old class files, unlike ProGuard.

**Comment by 0-x-2-2** [comment]
Oops, after upgrading ProGuard to the latest version from a few months old version it seems like this does work now but it spits out deprecation warnings instead errors. 

Perhaps it is more feasible to allow upgrading class files without the warning that is really only for backporting?
