### ISSUE TITLE
Obfuscation Techniques

### ISSUE THREAD

**Issue by hakanbcnk** [Guardsquare/proguard#303]
Which obfuscation techniques do you use?

**Comment by mrjameshamilton** [comment]
Hi @hakanbcnk ! ProGuard is primarily a Java shrinker (shrinking is sometimes also known as minification); it's not a security tool and doesn't implement any obfuscation techniques except for name obfuscation.

If you're looking for an Android security tool, you can refer [to DexGuard](https://www.guardsquare.com/blog/dexguard-vs.-proguard).
