### ISSUE TITLE
JDK 21 LTS support 

### ISSUE THREAD

**Issue by xberkhout** [Guardsquare/proguard#331]
The next Java release 21 (https://jdk.java.net/21/) will be an LTS release and to test early with virtual threads it would welcome if ProGuard would already support the internal version 65 so I can integrate it in my build system. Of course a beta is enough. 

I fully understand that now might be a bit early, but if it could be done when possible and at the latest together with the first release candidate of JDK 21 (https://openjdk.org/projects/jdk/21/), so early August that would be great.

Thank you already and kind regards,

Xander

**Comment by ansalond** [comment]
Is there any ETA about preliminary support for JDK21?

For your information, I plan to run some tests with the following changes: https://github.com/Guardsquare/proguard-core/compare/master...graalvm:proguard-core:da/jdk21

Of course this would only be a temporary workaround and I look forward to one of your snapshot builds.

Thanks!

**Comment by mrjameshamilton** [comment]
Hi @ansalond !

As far as I can tell, there's nothing in JDK21 that requires any special handling by ProGuard (for example, new class file attirbutes or bytecode instructions) so the changes you made should be sufficient. Can you make a PR?

Thanks!

**Comment by ansalond** [comment]
Hello @mrjameshamilton, thank you for the quick reply.

Here is the PR: https://github.com/Guardsquare/proguard-core/pull/92

Thanks!

**Comment by mrjameshamilton** [comment]
Thanks @ansalond ! Next I'll need to make a ProGuardCORE release and then update the dependency in ProGuard, then make a ProGuard release.

**Comment by xberkhout** [comment]
What is your estimation, when you could have a beta or release available?

**Comment by mrjameshamilton** [comment]
Hi @xberkhout ! I've made a [7.4.0-beta01 release](https://github.com/Guardsquare/proguard/releases/tag/v7.4.0-beta01) ; it'll be on Maven Central soon.

**Comment by xberkhout** [comment]
Thank you very much. I will test it the coming days with the Early Access of OpenJDK 21 in my build process.

**Comment by xberkhout** [comment]
I have today tested it with the first Release Candidate of JDK 21 (https://jdk.java.net/21/) and it works very well. Thank you very much.
