### ISSUE TITLE
Proguard GUI can be executed, but the operation interface cannot be displayed

### ISSUE THREAD

**Issue by JLU-WY** [Guardsquare/proguard#333]
I used to run version 7.3.0 of the GUI normally, but recently the interface stopped displaying without any error messages. I'm using the Windows 10 operating system, and I've tried starting it with different versions of JDK8 and JDK11, but the problem persists. I also downloaded the latest version 7.3.2, but encountered the same issue.

**Comment by tarowatermelon** [comment]
支持jdk11的程序吗
