### ISSUE TITLE
Does proguard work directly on apk files？

### ISSUE THREAD

**Issue by IMZGforever** [Guardsquare/proguard#334]
if i download a apk from f-droid，can I directly obfuscate this apk with proguard and output the obfuscated apk, and if so, how can I do it?

**Comment by mrjameshamilton** [comment]
Hi @IMZGforever ! No, ProGuard is only able to process Android applications as part of the Android build pipeline. ProGuard only supports AGP 4 - 7 and doesn't currently work with AGP 8 (#280).
