### ISSUE TITLE
Can we obfuscate spring boot war file ?

### ISSUE THREAD

**Issue by mazaharulhq** [Guardsquare/proguard#340]

**Comment by mrjameshamilton** [comment]
Yes, this should work. Please refer to the manual https://www.guardsquare.com/manual/home

If you have any further usages questions please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.
