### ISSUE TITLE
Cannot find super class of org/mangorage/mangobot/commands/tricks/TrickCommand$Data for Gson optimization. Please check your configuration includes all the expected library jars.

### ISSUE THREAD

**Issue by RealMangorage** [Guardsquare/proguard#358]
Got this error:

Cannot find super class of org/mangorage/mangobot/commands/tricks/TrickCommand$Data for Gson optimization. Please check your configuration includes all the expected library jars.

Im using a Shadowed Jar and then using Proguard with that.

-ignorewarnings
-allowaccessmodification

-verbose
-dontobfuscate
-optimizationpasses 1

-skipnonpubliclibraryclasses

-keepattributes Signature
-keepattributes *Annotation*
-keepattributes Signature

-dontwarn **
-dontpreverify
-dontusemixedcaseclassnames
-dontobfuscate
-dontshrink
-forceprocessing
-optimizations !com.google.**
-keep public class org.mangorage.mangobot.**

**Comment by mrjameshamilton** [comment]
Hi @RealMangorage ! This issue tracker here is intended for tracking bugs. Please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.
