### ISSUE TITLE
java.lang.ClassFormatError: Conflicting NestHost and NestMembers attributes in class file

### ISSUE THREAD

**Issue by kortenkamp** [Guardsquare/proguard#37]
We are using pro guard for many years now. Just recently (after we upgraded our codebase to use OpenJDK 13) we are experiencing runtime errors caused by NestHost and NestMembers attributes:

`java.lang.ClassFormatError: Conflicting NestHost and NestMembers attributes in class file`

It is very hard to create a minimal example, but I just would like to report this bug and hope that someone has an idea how it could be fixed.

**Comment by ingdas** [comment]
Hi, thanks for taking the time to report this. I have some followup questions.
- Did you try to disable proguard to check whether the issue is caused by us?
- Can you reliably trigger the exception?
- Are you comfortable sharing your jar with us so we can have a closer look at the problem?

**Comment by kortenkamp** [comment]
Hi, thanks for coming back to me! 

When I disable the optimisation, then everything works fine. I can reliably trigger the exception. And I could share the jar with you (but only privately, not on GitHub). Send me a mail with what you need exactly and I'll be happy to send it to you!

**Comment by ingdas** [comment]
In an ideal situation we have:
- an unprocessed jar
- the configuration you are using
- the processed and crashing jar

Once we can recreate the bug locally, it is usually pretty straightforward to find issues.
You can send your files to `ingmar (dot) dasseville (at) guardsquare (dot) com` and I'll have a look at it.

**Comment by karlvr** [comment]
I have experienced the same issue. Disabling optimisation similarly corrects the issue. Let me know if I can assist.

**Comment by mrieser** [comment]
I ran into the same problem.

Attached is a small case that reproduces the problem with ProGuard 7.0.1. Try running `java -jar lib/proguard-test.jar` (the original jar) and `java -jar lib/proguard-test-out.jar` (the proguard-processed jar). Source files and proguard-configuration are included as well in the archive.

[proguard-test.zip](https://github.com/Guardsquare/proguard/files/5990104/proguard-test.zip)

**Comment by mrjameshamilton** [comment]
Hi @mrieser ! Thanks for the sample, that's very helpful. It seems that the class merging optimizations do not take into account nest-based access control and a nest host and member get merged into the same class. You can workaround this by disabling class merging:

```
-optimizations !class/merging/*
```
