### ISSUE TITLE
Support K2

### ISSUE THREAD

**Issue by mgroth0** [Guardsquare/proguard#376]
With Proguard 7.4.1 and Kotlin 2.0.0-Beta2 we get the error "Kotlin versions up to 1.9 are supported."

I am sure that Proguard support for K2 is coming, but I couldn't find an issue or mention of this anywhere. Creating this so I can get notified when it is available.

**Comment by timeking** [comment]
@mgroth0 , it seems you are using incorrect gradle kotlin plugin. Try to use 2.0.0-Beta2 (Beta5 now). I see proguard uses version from the dependency. 
FYI: it have an error still for Kotlin 2.0.0 metadata, but another one: 

Encountered corrupt @kotlin/Metadata for class com/example/Example (version 2.0.0).

**Comment by ellet0** [comment]
The stable version of Kotlin 2.0.0 is already out before a day. Getting the exact same error ` Kotlin versions up to 1.9 are supported.`

Looking forward to see the new version of Proguard

**Comment by ellet0** [comment]
It looks like 7.5.0 might already solve this issue but the changes haven't published yet, if you take a look at [Gradle Task](https://github.com/Guardsquare/proguard?tab=readme-ov-file#gradle-task) section you will see 7.5.0, also in the commits history

Looking forward to see the new version.

**Comment by mipastgt** [comment]
Is there an ETA for the K2 support now that it has been officially released? It would be nice to be able to build Compose Multiplatform apps again. See: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1716746013470279

**Comment by mrjameshamilton** [comment]
ProGuard 7.5 has just been published with Kotlin 2 support.
