### ISSUE TITLE
keep rule not working with annotation nested inside class

### ISSUE THREAD

**Issue by pstreef** [Guardsquare/proguard#379]
I'm trying to keep classes with an annotation defined inside of a class. The picocli `@Command` annotation is nested inside CommandLine class like:

```
public class CommandLine{
    ...
    @Retention(RetentionPolicy.RUNTIME)
        @Target({ElementType.TYPE, ElementType.LOCAL_VARIABLE, ElementType.FIELD, ElementType.PACKAGE, ElementType.METHOD})
    public @annotation Command {
        ...
    }
}
```

Does not work:
```
-keep @picocli.CommandLine.Command class com.example.proguard.** { ** builder(); <init>(...); }
```

but using a wildcard does work:
```
-keep @picocli.** class com.example.proguard.** { ** builder(); <init>(...); }
```

Here is a playground with an example rule (I assume this also shares the uploaded sample code?)
https://playground.proguard.com/p/jbScvf

**Comment by rubenpieters** [comment]
Thanks for the reproducible proguard playground link! Makes it easier to understand your issue.

I believe the problem you're running into is that you're using the `.` to target the inner class. ProGuard follows the hierarchy of how the inner class is compiled by the java compiler, which will be in a separate class file named `CommandLine$Command`.

Changing the rule to the following, taking into account the `$` needed to target the inner class, works for me on the playground you shared.

```
-keep @picocli.CommandLine$Command class com.example.proguard.** { ** builder(); <init>(...); }
```

Can you confirm that this works for you as well?

**Comment by pstreef** [comment]
Hi @rubenpieters 
Yes, that was the mistake, I had used the $ for inner classes already but did not make the link that that was also needed for this annotation. Thanks for the quick response!
