### ISSUE TITLE
ProGuard status?..

### ISSUE THREAD

**Issue by Miha-x64** [Guardsquare/proguard#38]
Hello. I'm trying to shrink a JavaFX application and the last public version of ProGuard, `6.3.0beta1` (I use Gradle task), says it supports only Java 10 bytecode. But, according to the source code, ProGuard supports even Java 14.
What's the status of ProGuard project, will there be a release?
Thanks.

**Comment by dzan** [comment]
hi @Miha-x64,

ProGuard 7 is released today and has the relevant release note for Java 14. Complete support for 14 is tracked in #32

**Comment by Miha-x64** [comment]
Glad to know you're in, and thanks for all you're doing!
