### ISSUE TITLE
Anonymous Classes Inside Other Anonymous Classes Produce "Unresolved references to program class members" Warning

### ISSUE THREAD

**Issue by jmohrmann** [Guardsquare/proguard#384]
This issue seems to be the result of strange interplay between the Eclipse Java Compiler as reflected in Eclipse 2023-12 and ProGuard. I'm not sure which is causing the problem. 

In short, when obfuscating a .jar file created with code compiled by Eclipse, I now get a warning (which I never got before with the same code) which complains that it cannot find methods in anonymous classes that are inside another anonymous class. The code below is an example of what produces this warning:

```
public class Main {

public static void main(String[] args) {
    Main main = new Main();
    main.run();
}

public void run() {
    FirstClass fc = new FirstClass() {
        SecondClass sc = new SecondClass() {
            @Override
            public void print() {
                System.out.println("Second Class Override.");
            }
        };
        
        @Override
        public void print() {
            System.out.println("First Class Override.");
            sc.print();
        }
    };
    fc.print();
}

public class FirstClass {
    public void print() {
        System.out.println("First Class");
    }
}

public class SecondClass {
    public void print() {
        System.out.println("Second Class");
    }
}
}
```

This only started happening after I updated my Eclipse version from an older version to 2023-12. A colleague of mine with an older eclipse says obfuscating with ProGuard still works fine for him.

More information is included [here](https://stackoverflow.com/questions/77889546/proguard-doesnt-like-anonymous-classes-inside-other-anonymous-classes-after-lat)

**Comment by aumann** [comment]
We have a similar problem. We've updated our (maven) tycho version, which compiles with a newer JDT, and now we get an additional warning from proguard. 

This is approximately the pattern we have:

```java
// package a;

public interface A {
  default void m() {
    throw new UnsupportedOperationException("");
  }
}

public class L {
  public void onEvent() {}
  public void other() {}
}

// package b;

public class AImpl implements a.A {
  public void addListener(L listener) {
    
  }
}

public class OuterBase {
  A createA() {
    return new AImpl();
  }
}

// package c;

public class ObfuscationIssue extends b.OuterBase {
  public void other() {
    // here, the ref works
    createA();
  }
  
  @Override
  a.A createA() {
    // ObfuscationIssue$123
    return new b.AImpl() {
      private final java.util.List<java.util.function.Consumer<String>> list;
      { // anon constructor
        list = java.util.List.of();
        // probably unrelated: we have a ref like a.A.EnumXX.LITERAL, here
        
        // anon a.L is ObfuscationIssue$123$1
        addListener(new a.L() {
          @Override public void onEvent() {
            
            list.forEach(c -> c.accept("thing"));
          }
        });
      }
      @Override
      public void m() {
        // do stuff
      }
    };
  }

}

```

The warning we now get is `c.ObfuscationIssue$123$1: can't find enclosing method 'A createAl()' in program class c.ObfuscationIssue$123`

I hope this helps, please let me know if you need something else / more info.

**Comment by jmohrmann** [comment]
Well, it appears this may have been an issue with Eclipse and _not_ with ProGuard. I have just updated to the latest 2024-03 version of Eclipse, and the problem does not occur anymore. Even using ProGuard 5.2.1, the project builds and obfuscates fine with no warnings about anonymous classes that have to be ignored for the obfuscation to complete successfully.
