### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: proguard.optimize.gson._OptimizedJsonWriter

### ISSUE THREAD

**Issue by SudoDios** [Guardsquare/proguard#391]
How to fix it ?
Caused by: java.lang.ClassNotFoundException: proguard.optimize.gson._OptimizedJsonWriter

**Comment by mrjameshamilton** [comment]
Hi @SudoDios ,

As a workaround, you can try disabling the GSON optimization with `-optimizations !library/gson` to see if that helps (see the manual https://www.guardsquare.com/manual/configuration/optimizations )

For investigating and fixing the issue, it would be useful to have a reproducible sample.
