### ISSUE TITLE
Obfuscate

### ISSUE THREAD

**Issue by vineetbillorey** [Guardsquare/proguard#416]
How can I obfuscate Springboot web app

**Comment by mrjameshamilton** [comment]
Hi @vineetbillorey !

There is an example for Spring Boot [here](https://github.com/Guardsquare/proguard/tree/master/examples/spring-boot). You'll also find some useful information in the [manual](https://www.guardsquare.com/manual/home) in how to configure ProGuard.

This issue tracker here is intended for tracking bugs. Please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.

**Comment by vineetbillorey** [comment]
This if for jar file, I need for war in tomcat.

[Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) has also not responded
