### ISSUE TITLE
jar in tomcat

### ISSUE THREAD

**Issue by vineetbillorey** [Guardsquare/proguard#418]
How can I run this jar in tomcat?

**Comment by mrjameshamilton** [comment]
Hi @vineetbillorey ! This issue tracker here is intended for tracking bugs. Please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) to continue the discussion where you can get tips and advice on your configuration from our team of engineers and skilled community members.
