### ISSUE TITLE
Proguard (obfuscator) for J2ME Wireless Toolkit 2.2 (2005)

### ISSUE THREAD

**Issue by 3dcinetv** [Guardsquare/proguard#420]
Hi. I recently came across [this page](https://www.mobilefish.com/emulators/j2me_wt/j2me_wt_quickguide_22_build.html) which requires the proguard version from 2005-2006. 
The environment required for it to work is the j2me_wireless_toolkit-2_2 + [J2SE SDK 1.4.2 
](https://www.oracle.com/java/technologies/java-archive-javase-v14-downloads.html) 
I understand those Java versions were EOL, but I still need to replicate the steps on [the page.](https://www.mobilefish.com/emulators/j2me_wt/j2me_wt_quickguide_22_build.html)

What version of Proguard should I download for Windows XP (home) SP2, 2005 Java environment?
Please help.
Thanks.
![proguard obfuscator](https://github.com/Guardsquare/proguard/assets/11066585/6b761c3d-d10a-45ac-89b0-194b9322c267)

**Comment by mrjameshamilton** [comment]
Hi @3dcinetv ! You can find older versions of ProGuard on [SourceForge](
https://sourceforge.net/projects/proguard/files/proguard/), where the project used to be hosted, all the way back to version 1.0 from 2002.

**Comment by 3dcinetv** [comment]
Fantastic, the site even categorizes versions per year. Thank you. It all seems to point to version 3.3 or 3.4. This was very helpful!
