### ISSUE TITLE
java.lang.IllegalArgumentException: Value "i" is not a reference value [proguard.evaluation.value.UnknownIntegerValue]

### ISSUE THREAD

**Issue by taiphamevizi** [Guardsquare/proguard#47]
![proguared](https://user-images.githubusercontent.com/64018169/84855444-55d3a600-b08e-11ea-9cb7-6f60bbc242ac.png)

I have using "com.guardsquare:proguard-gradle:7.0.0"  but I cannot build app, it always show Exception with Kotlin class.
Please help to find any causing, thank you so much.

**Comment by ingdas** [comment]
Hi, thanks for taking the time to report this to us. Can you tell us which version of GSON you are using? Can you also share your full Proguard build log? Is your application fully in Kotlin?

**Comment by taiphamevizi** [comment]
> Hi, thanks for taking the time to report this to us. Can you tell us which version of GSON you are using? Can you also share your full Proguard build log? Is your application fully in Kotlin?

I have using Gson 2.8.6 and my project code both java and kotlin, I dont have build log at time, If I have add this option "-dontoptimize" in proguard file then I can build, but when I remove it then I cannot build. Thanks

**Comment by dedee** [comment]
Wanted to try the gson optimization feature with a small sample project, but it fails with the error message, reported above. When switching back from 7.0.1 to 6.2.2 it works. Looks like the whole feature is broken in latest releases.

**Comment by mrjameshamilton** [comment]
Hi @dedee , would you be able to share your sample project?

**Comment by dedee** [comment]
[proguard_gsontest.zip](https://github.com/Guardsquare/proguard/files/5663861/proguard_gsontest.zip)

**Comment by doudasek** [comment]
Is there a workaround for this bug by disabling optimization only for Gson?

**Comment by mrjameshamilton** [comment]
Indeed, until we get to the bottom of the problem you can turn off Gson optimizations with:

```
-optimizations !library/gson
```

**Comment by mrjameshamilton** [comment]
Hi all, I've committed a fix for this. It's on master but not yet in a release. You can test it out by building ProGuard yourself https://github.com/Guardsquare/proguard#-building-proguard
