### ISSUE TITLE
Can i use it with byte-buddy library ?

### ISSUE THREAD

**Issue by XhstormR** [Guardsquare/proguard#50]
Please check this issues: https://github.com/raphw/byte-buddy/issues/884

Can i turn off all optimization options for a certain class, or skip a certain class to avoid some impact？ Or is this a bug? Can you fix it?

**Comment by EricLafortune** [comment]
Looking at the referenced bug report: ProGuard generates StackMapTable attributes with the preverification information that the JVM requires. A quick test running the processed method with the JVM shows that the attribute should be fine. Still, Byte Buddy has a problem with it.

You could re-enable obfuscation and disable preverification (`-dontpreverify`) to remove all StackMapTable attributes, but then Byte Buddy has to generate the attributes to make the code acceptable to the JVM.

**Comment by XhstormR** [comment]
After I added this `-dontpreverify` option, the generated jar package could not be run, and an `java.lang.VerifyError` exception was thrown:

```
D:\IdeaProjects\memshell\build\libs>java -jar memshell-1.0-SNAPSHOT-min.jar
Error: unable to initialize main class com.xhstormr.app.MainKt
Reason: java.lang.VerifyError: Expecting a stackmap frame at branch target 23
Exception Details:
  Location:
    com/xhstormr/app/MainKt.main([Ljava/lang/String;)V @9: if_icmpeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2a12 08b8 0030 2abe 059f 000e 1206 4cb2
    0000010: 0024 2bb6 0032 b12a 0332 b800 3340 2a04
    0000020: 324e b800 2d4b b800 3659 1203 b800 2fb9
    0000030: 003b 0100 5912 04b8 002f 593a 043a 0519
    0000040: 0419 053a 0659 3a04 1201 b800 3019 0612
    0000050: 0ab8 0030 1904 c000 1410 4003 1006 b800
    0000060: 2c59 3605 02a0 0008 1906 a700 1119 0403
    0000070: 1505 b600 3459 1202 b800 2fb8 0033 3705
    0000080: 1f09 9499 000d 2a1f b800 352d b800 31b1
    0000090: 1205 4cb2 0024 2bb6 0032 b800 2a59 1207
    00000a0: b800 2fc0 0015 4cbb 001c 59b7 0037 c000
    00000b0: 1d4d 2bb9 003a 0100 4c2b b900 3d01 0099
    00000c0: 002b 2bb9 003e 0100 593a 04c0 000d b600
    00000d0: 2b16 05b8 0035 b800 2e04 8299 ffde 2c19
    00000e0: 04b9 003c 0200 57a7 ffd2 2cc0 001f c000
    00000f0: 15b9 003a 0100 4c2b b900 3d01 0099 0057
    0000100: 2bb9 003e 0100 c000 0d59 4db8 0027 3a04
    0000110: 1904 5912 0bb8 002f b600 2912 09b6 0038
    0000120: 3607 1904 b600 28a7 000b 4b19 04b6 0028
    0000130: 2abf 1507 9900 1db2 0024 2cb6 0032 b200
    0000140: 2614 0022 b600 392a 2cb6 002b 2db8 0031
    0000150: b1a7 ffa6 b200 250a b600 39a7 ff35
  Exception Handler Table:
    bci [272, 290] => handler: 298
```

According to the [official documentation](https://www.guardsquare.com/en/products/proguard/manual/usage), this option seems to be global and cannot be enabled for a single class.

This is the processed jar package:[test.zip](https://github.com/Guardsquare/proguard/files/4810936/test.zip)

**Comment by EricLafortune** [comment]
That's correct, if ProGuard doesn't preverify the code (create the StackMapTable attributes, disabled with `-dontpreverify`), then Byte Buddy still has to preverify the code, in order to make it acceptable to the JVM. No doubt Byte Buddy implements preverification, but I don't know how to enable it. Overall, the original error still seems like a bug in Byte Buddy.

**Comment by mrjameshamilton** [comment]
Last bytebuddy reply: https://github.com/raphw/byte-buddy/issues/884#issuecomment-648115760

> Byte Buddy requires the original format of the stack map table to retain it's inlineability. Byte Buddy does not run the code, it uses it as a template. If ProGuard tempers with the stack map frames, no matter if the JVM can accept it, the templating engine cannot merge the frames into the original method anymore.

**Comment by abelthefirst** [comment]
Hello. Not sure it makes sense to leave comments here, otherwise I'll create a new question/issue. Given the above answer, what would be a resolution here? Seems like that issue can not be fixed on the Byte Buddy side, is there anything, that can be done on the ProGuard side?

**Comment by mrjameshamilton** [comment]
Hi @abelthefirst ! I'm not familiar with the inner workings of Byte Buddy and exactly what ProGuard is doing that causes it to not to work. Are you able to provide a complete sample?

The code that ProGuard produces should be valid JVM code with valid StackMapTable attributes (unless there is a bug or `-dontpreverify` is used).

Maybe @raphw from the Byte Buddy side (https://github.com/raphw/byte-buddy/issues/884#issuecomment-648115760) can provide some insight?

**Comment by abelthefirst** [comment]
Hi @mrjameshamilton, thank you for the update. I'll try to compile an example.

**Comment by raphw** [comment]
Have you been using a recent version? Byte Buddy should handle all forms of obfuscation, but there can be of course an unexpected pattern. Ideally, you'd report this with a reproduction if it happened.

**Comment by abelthefirst** [comment]
Hi @mrjameshamilton. I just realised, that I've being using not ProGuard, but DexGuard (with an option specific to DexGuard). Does it make sense to continue our discussion here or I better use DexGuard support channel?

**Comment by valentinbrad-wolfpack** [comment]
> Have you been using a recent version? Byte Buddy should handle all forms of obfuscation, but there can be of course an unexpected pattern. Ideally, you'd report this with a reproduction if it happened.

Hi, 
I'm still getting an error when I use obfuscation and ByteBuddy for Android using the recent version (1.12.8).

This is how the obfuscation looks like in my Gradle file:
```
...
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
        }
    }
...
//ByteBuddy dependency 
implementation 'net.bytebuddy:byte-buddy-android:1.12.8'
...
```

I have this line in proguard-rules.pro file:
`-keep class net.bytebuddy.** {*;}
`

This is the function where I use ByteBuddy:

```
fun interceptClipboardService(service: Any): Any? {
        val strategy = AndroidClassLoadingStrategy.Wrapping(
            getDir("generated", Context.MODE_PRIVATE)
        )

        val dynamicType: Class<*>? = ByteBuddy()
            .subclass(service.javaClass)
            .method(ElementMatchers.named("isEnabled"))
            .intercept(FixedValue.value(false))
            .make()
            .load(service.javaClass.classLoader, strategy)
            .loaded

        val objenesis = ObjenesisStd()
        return objenesis.newInstance(dynamicType)
}
```

And I get this error:

```
Fatal Exception: java.lang.IllegalStateException
Could not resolve dispatcher: e.a.b.c.b.b.translate [class e.a.b.a.a.b, class [B, class e.a.b.c.b.a, class e.a.b.c.a, class e.a.b.c.c.h]

net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler$Dispatcher$Unavailable.setTargetApi (AndroidClassLoadingStrategy.java:21)
net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler.makeDefault (AndroidClassLoadingStrategy.java:9)
net.bytebuddy.android.AndroidClassLoadingStrategy$Wrapping.<init> (AndroidClassLoadingStrategy.java)
...
```

@raphw do you know how can I prevent the obfuscation for ByteBuddy? Thanks 🙏
