### ISSUE TITLE
After upgrading android build:gradle:4.0.0 shows me error in proguard

### ISSUE THREAD

**Issue by attaullahpro** [Guardsquare/proguard#51]
After upgrading android build:gradle:4.0.0 shows me Unresolved class name error in proguard.

```
-keep class rx.** { *; } // unresolve
-keep class org.apache.** {*;} // unresolve
-keep class org.apache.http.** { *; } // unresolve
-keep class org.apache.james.mime4j.** { *; } // unresolve
-dontwarn retrofit2.Platform$Java8 // error at $ sign
```

**Comment by EricLafortune** [comment]
Can you provide more details?
* How is ProGuard integrated in your gradle build? Is this an Android project?
* ProGuard doesn't have an eeror message "Unresolved class name error". What is the complete error message? Do you have a stack trace (gradle option `-s`)? Do you see any other differences in the ProGuard console output, compared with a working build (gradle option `-i` to see details)?

**Comment by attaullahpro** [comment]
I integrated like this,
```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
}
```

I can build without any error but the issue is that when I open **proguard-rules.pro** then following errors occur, Unresolved class name

**Comment by mrjameshamilton** [comment]
Hi @attaullahpro, this is actually an Android Studio feature and not related to ProGuard: https://developer.android.com/studio/releases?hl=hr#4-0-0-smart-code-shrinker-rules
