### ISSUE TITLE
-keepkotlinmetadata doesn't work as expected in version 7.0.0 

### ISSUE THREAD

**Issue by pbielicki** [Guardsquare/proguard#53]
### Problem description
In one of our module we have some Kotlin code that we don't want to obfuscate thus we have this entry in the config:
```
-keepkotlinmetadata
-keep class org.gradle.kotlin.dsl.** { *; }
```

This makes the `proguard-gradle` task complain:
```
Execution failed for task ':xxx:proguard'.
> Library class [org/gradle/kotlin/dsl/TypeOfExtensionsKt$typeOf$1] doesn't store attributes
```
This is the file [TypeOfExtensions.kt](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/TypeOfExtensions.kt) that is "problematic".

As a workaround I found that this piece of configuration actually works:
```
-keep class kotlin.Metadata { *; }
-keep class org.gradle.kotlin.dsl.** { *; }
```

TBH I'd expect `-keepkotlinmetadata` to have exactly the same effect as `-keep class kotlin.Metadata { *; }` but it's not the case.

### Note
It worked all fine in the previous version 6.2.2 - we had neither `-keepkotlinmetadata` nor  `-keep class kotlin.Metadata { *; }` in our configuration files.

**Comment by mrjameshamilton** [comment]
Hi @pbielicki , indeed there was some problem with the `-keepkotlinmetadata` option which we've [fixed here](https://github.com/Guardsquare/proguard/commit/0b89e1c1486b197caadeeed8151b5cd252803f38), the `-keepkotlinmetadata` option should now have the same effect as `-keep class kotlin.Metadata { *; }`. This has not yet been released but you could [build ProGuard from source](https://github.com/Guardsquare/proguard#-building-proguard).

**Comment by pbielicki** [comment]
👍  awesome @mrjameshamilton - thank you!
