### ISSUE TITLE
can proguard read <java.home>/lib/modules from openjdk-14?

### ISSUE THREAD

**Issue by itmeisterei** [Guardsquare/proguard#57]
although proguard reports
```
Reading library directory [/usr/lib/jvm/java-14-openjdk-14.0.1.7-2.rolling.fc32.x86_64/lib/modules] (filtered)
Initializing...
```
there are alot of
```
Note: the configuration refers to the unknown class 'java.lang.String'
Note: the configuration refers to the unknown class 'java.sql.Driver'
Note: the configuration refers to the unknown class 'java.lang.System'
```
and proguard fails at the end.

`jimage extract --dir=rt /lib/jvm/java/lib/modules` and using `-libraryjars rt/java.base` within the config file works around the problem, but this feels not quite right.

**Comment by EricLafortune** [comment]
The word `(filtered)` in the console output suggests that your are trying to filter on the jmod files in the modules directory. ProGuard expects filters on archives and files in a semicolon-separated list, per archive type. From the documentation:
```
 classpathentry([[[[[[[jmodfilter;]aarfilter;]apkfilter;]zipfilter;]earfilter;]warfilter;]jarfilter;]filefilter)
```
Even with empty filters, you need the right number of semicolons (which got out of hand when the number of archive types kept increasing). You probably want something like
```
-libraryjars modules(java.base.jmod;;;;;;;)
```
Alternatively, you can also specify each jmod file with its own `-libraryjars` option.

**Comment by leonbloy** [comment]
I have the same problem (openJDK 17), and it seems to me that the answers here do not help.

> suggests that your are trying to filter on the jmod files in the modules directory.

No,. `modules` is not a directory but a file that packs all the JRE modules in OpenJDK.

https://www.herongyang.com/Java-Tools/jimage-Java-Image-File-Format.html

The question is whether proguard understand it, and what is the format to pick some/all of its modules.

I've tried several syntaxes, and none worked.
