### ISSUE TITLE
Overwrite module-info

### ISSUE THREAD

**Issue by GogoTrash** [Guardsquare/proguard#67]
I have a multi-module project and I want the multiple jars to be obfuscated at the end.
When I build the jar of each sub-project, the module-info of each is good but when I use Proguard, I use _-keep class module-info_ and _-keepattributes module*_ options and at the end each jar have the same module-info (the module-info of the root sub-project). 
I think is because the module-info.class is at the root of each jar (with the same name and at the same place) and Proguard overwrite the others with the first he found.

**Comment by EricLafortune** [comment]
That's a tricky problem indeed. ProGuard always has a single, unique representation for each class, so the first module-info.class always wins. If the module-info classes can remain completely unchanged, you can rename them in the input and output (with `->` in the filter), in such a way that ProGuard treats them as (different) plain resource files instead of classes:
```
-injars  input1.jmod (module-info.class->module-info1,**)
-oujtars output1.jmod(module-info1->module-info.class,**)

-injars  input2.jmod (module-info.class->module-info2,**)
-oujtars output2.jmod(module-info2->module-info.class,**)
```

**Comment by GogoTrash** [comment]
What if they need to be changed?

**Comment by EricLafortune** [comment]
I don't see a simple solution there. You could obfuscate the modules one by one, with mapping files for the obfuscated library modules, but that is convoluted. You could also post-process the module-info classes one by one, adding the obfuscated module-info classes to the obfuscated module jars.

**Comment by GogoTrash** [comment]
I found a good compromise with the _-keeppackagenames_ and your options. 
```
-injars  input1.jar(module-info.class->module-info1,**)
-oujtars output1.jar(module-info1->module-info.class,**)

-injars  input2.jar(module-info.class->module-info2,**)
-oujtars output2.jar(module-info2->module-info.class,**)

-keeppackagenames **
```
This allows me to obfuscate all my projects without having to modify the module-info's, because the packages don't change their names.
