### ISSUE TITLE
Proguard -keep interface param names not work

### ISSUE THREAD

**Issue by simonsfan** [Guardsquare/proguard#70]
Hi：
i use proguard to confuse code，which used it in maven，like this：

> <build>
        <plugins>
            <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.0.14</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <proguardVersion>6.2.2</proguardVersion>
                    <obfuscate>true</obfuscate>
                    <attachArtifactClassifier>pg</attachArtifactClassifier>
                    <options>
                        <option>-target 1.8</option>
                        <option>-dontshrink</option>
                        <option>-dontoptimize</option>
                        <option>-dontskipnonpubliclibraryclasses</option>
                        <option>-dontskipnonpubliclibraryclassmembers</option>
                        <option>-allowaccessmodification</option>
                        <option>-useuniqueclassmembernames</option>
                        <option>-adaptclassstrings</option>
                        <option>-dontusemixedcaseclassnames</option>
                        <option>-keeppackagenames</option>
                        <option>-keepparameternames</option>
                        <option>-keepattributes
                            Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,LocalVariable*Table,*Annotation*,Synthetic,EnclosingMethod
                        </option>
                        <option>
                            -keepclassmembers public class *{void set*(***);*** get*();}
                        </option>
                        <option>
                            -keepclasseswithmembers public class * { public static void main(java.lang.String[]);}
                        </option>
                        <option>
                            -keep interface com.cpic.framework.admin.sys.mapper.** { *; }
                        </option>
                        <option>-keepclassmembers enum * { *; }</option>
                        <option>-keep class com.cpic.framework.admin.sys.mapper.** { *; }</option>
                        <option>-keep class com.cpic.framework.admin.sys.mapper.** { &lt;methods&gt;; }</option>
                        <option>-dontwarn **</option>
                    </options>
                    <libs>
                        <lib>${java.home}/lib/rt.jar</lib>
                    </libs>
                    <inFilter>com/cpic/framework/admin/sys/**</inFilter>
                    <injar>classes</injar>
                    <injar>${project.build.finalName}.jar</injar>
                    <outjar>${project.build.finalName}-pg.jar</outjar>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.sf.proguard</groupId>
                        <artifactId>proguard-base</artifactId>
                        <version>6.2.2</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
</build>

point here：
`<option>-keep class com.cpic.framework.admin.sys.mapper.** { *; }</option>`

i want to keep the package  of “com.cpic.framework.admin.sys.mapper.**” not to be confused，include class、method、method parameter，but the result is the parameter of method was changed（attention there：it`s all interface on the package），like this：

before：
`public interface AppRegisterFunction {
    void dealPostProcess(String appModuleCode, String appAddress);
}`

after confused：
`public interface e {
    void dealPostProcess(String var1, String var2);
}
`
thanks~

**Comment by EricLafortune** [comment]
Keeping **class names** should worrk fine if you don't have any typos in your configuration. You can try `-printconfiguration config.txt` to check the configuration and `-printseeds seeds.txt` to check which classes, fields, and methods it matches.

The **parameter names** are not part of the essential bytecode, just debug information. ProGuard removes this information by default, but depending on which aspect you need exactly, you can keep it with
```
-keepattributes LocalVariableTable, LocalVariableTypeTable, MethodParameters
```
as you've already done, except for the last one. Your decompiler may or may not recognize these attributes.

**Comment by simonsfan** [comment]
cool ! it works. thank you.

**Comment by javaone199** [comment]
> 

Tried:
` -keepattributes LocalVariableTable, LocalVariableTypeTable, MethodParameters`

It did not work for interfaces. Interface method parameters are still obfuscated as s1,s2,...
