### ISSUE TITLE
Unit tests failed to compile after source code java obfuscation 

### ISSUE THREAD

**Issue by sumanjara** [Guardsquare/proguard#74]
Hi,
We are trying to obfuscate a module A and with proguard we got a obfuscated module A.

This module A is refered as a run time jar in Auto tests project. The auto tests are failing now due to its not finding the class name( obfuscated class name).

We wanted to test the obfuscated code in Auto test module. How can we do this?

We are using gradle for project. We tried with applymapping but didnt see any example in docs or online.

**Comment by sumanjara** [comment]
Label as usage question

**Comment by mrjameshamilton** [comment]
Hi @sumanjara ,

Thanks for your question! The aim of the issue tracker here is to track technical issues and bugs.

For usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
