### ISSUE TITLE
Multimodule Java shrink removing classes and problems in dependent modulea

### ISSUE THREAD

**Issue by sumanjara** [Guardsquare/proguard#75]
Module A 
Module B depends on ModuleA
Module C depends on Module B

When i obfuscate moduleA, ModuleB is failing. What settings or approach in this case.

I dont want to obfuscate ModuleB.

Shrink also removing some classes from ModuleA, which are used in ModuleB.

**Comment by mrjameshamilton** [comment]
Hi @sumanjara ,

Thanks for your question! The aim of the issue tracker here is to track technical issues and bugs.

For usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
