### ISSUE TITLE
5.3.3 to 6.0.3: Value "f" is not a reference value (UnknownFloatValue)

### ISSUE THREAD

**Issue by Lonzak** [Guardsquare/proguard#8]
We had to update our proguard version but now we get a strange error. Any idea how to fix it, or is it a proguard issue?
The lib is https://repository.jboss.org/maven2/javax/media/jai-core/1.1.3/jai-core-1.1.3.jar

[proguard] Unexpected error while evaluating instruction:
 [proguard]   Class       = [com/sun/media/jai/opimage/ImageFunctionOpImage]
 [proguard]   Method      = [computeRect([Ljavax/media/jai/PlanarImage;Ljava/awt/image/WritableRaster;Ljava/awt/Rectangle;)V]
 [proguard]   Instruction = [357] aaload
 [proguard]   Exception   = [java.lang.IllegalArgumentException] (Value "f" is not a reference value [proguard.evaluation.value.UnknownFloatValue])
 [proguard] Unexpected error while performing partial evaluation:
 [proguard]   Class       = [com/sun/media/jai/opimage/ImageFunctionOpImage]
 [proguard]   Method      = [computeRect([Ljavax/media/jai/PlanarImage;Ljava/awt/image/WritableRaster;Ljava/awt/Rectangle;)V]
 [proguard]   Exception   = [java.lang.IllegalArgumentException] (Value "f" is not a reference value [proguard.evaluation.value.UnknownFloatValue])
 [proguard] Error: java.lang.IllegalArgumentException: Value "f" is not a reference value [proguard.evaluation.value.UnknownFloatValue]

**Comment by netomi** [comment]
What proguard version do you use to reproduce the issue?
What version did you use previously which seems to work?

**Comment by Lonzak** [comment]
The headline gives it away:
"previous working version": 5.3.3
"newer not working version": 6.0.3

**Comment by netomi** [comment]
I missed that, we will try to reproduce the issue. Do you have a chance to test it with the latest version 6.2.0 and see if the issue is still present?
Also a simple sample project would be helpful.

**Comment by ingdas** [comment]
Still present in 6.2.0. I minimized it to the following small program.

My first guess was that it would be the generalization between double[] and double[][], but I excluded that already. 

```
public class Main {
    public static void main(String[] args) {
        t(true);
    }

    public static void t(boolean b) {

        Object data = b ? new double[9]
                        : new double[2][8];

        double[] real = ((double[][]) data)[0];
    }
}
```

**Comment by Lonzak** [comment]
@ingdas  You were quicker than I - thanks for the mini example!

**Comment by netomi** [comment]
Thanks for the simple sample.
As expected this should result in a runtime exception:

java.lang.ClassCastException: double[] cannot be cast to double[][]

The processing should take this into account, I could workaround it using a keep rule:

-keep,includecode class Main {
    void t();
}

In our internal tests such a keep rule was not sufficient for the jai library, so I wonder if it reproduces the exact same problem. Needs further investigation.

**Comment by Lonzak** [comment]
But the real code doesn't necessarily go into a CCE.

```
	public static void main(String[] args) {
		Mayne m = new Mayne();
		m.computeRect();
		m.t();
	}
	
    protected void computeRect() {
        
    	boolean function = true;
        //int dataType = DataBuffer.TYPE_DOUBLE;
        int dataType = DataBuffer.TYPE_FLOAT;
        
        int length = 6;
        
        Object data;
        if (dataType == DataBuffer.TYPE_DOUBLE) {
            data = function ? new double[2][length] : new double[length];
        } 
        else {
            data = function ? new float[2][length] :  new float[length];
        }
        
        if (dataType == DataBuffer.TYPE_DOUBLE) {
            double[] real = function ? ((double[][]) data)[0] : ((double[]) data);
            double[] img = function ? ((double[][]) data)[1] : null;
            
            System.out.println(Arrays.toString(real));
            System.out.println(Arrays.toString(img));

        } 
        else { // not double precision
            float[] real = function ? ((float[][]) data)[0] : ((float[]) data);
            float[] img = function ? ((float[][]) data)[1] : null;
            
            System.out.println(Arrays.toString(real));
            System.out.println(Arrays.toString(img));
        }
    }
```

**Comment by netomi** [comment]
Thanks for the more realistic example.
We could fix the problem already and will include it in a 6.2.1 release.

**Comment by Lonzak** [comment]
So do I need to use?
```
-keep,includecode class Main {
void t();
}
```

**Comment by netomi** [comment]
No, with the fixed version of ProGuard, no keep rule will be needed.
The suggested keep rule was a workaround for the posted example to make the current available Proguard release able to process the sample.
