### ISSUE TITLE
Using ProGuard to remove dead code in a spring application preferably using Maven

### ISSUE THREAD

**Issue by aakriti-kedia** [Guardsquare/proguard#80]
I tried downloading [ProGuard](https://github.com/Guardsquare/proguard) and running the examples folder. I do not want to run the android sample project. I want to use ProGuard just to remove dead code from my Spring Application. But I do not understand what needs to be mentioned in the [build.gradle](https://github.com/Guardsquare/proguard/blob/master/examples/android/build.gradle) file instead of the android block and what other files should be a part of my Spring application and is the ANDROID_SDK needed even if it is a spring application.   Are there any resources which can help get started with **ProGuard to remove dead code from Spring application** ? If not, can some HelloWorld application or some readme with all required details be provided to run ProGuard on a spring project preferably using maven ?

**Comment by mrjameshamilton** [comment]
Hi @aakriti-kedia, there is now a [Spring Boot example application](https://github.com/Guardsquare/proguard/tree/master/examples/spring-boot) in the examples directory (though it is gradle based). 

If the sample doesn't help to answer your question please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice.
