### ISSUE TITLE
Kotlin Gradle DSL Examples?

### ISSUE THREAD

**Issue by sithys** [Guardsquare/proguard#82]
I read through the examples and they are all written in Groovy. Are there any example build.gradle.kts files written in the Kotlin Gradle DSL that demonstrate the features of proguard?

**Comment by mrjameshamilton** [comment]
Hi @sithys! I've added a Gradle Kotlin DSL sample here: https://github.com/Guardsquare/proguard/tree/master/examples/gradlekotlindsl

Hope that helps!
