### ISSUE TITLE
Kotlin Library Standalone Examples?

### ISSUE THREAD

**Issue by sithys** [Guardsquare/proguard#83]
I am getting 7614 unresolved references to classes or interfaces and 42 errors during Kotlin metadata initialization when trying to run proguard on my Kotlin jar. The jar is being created with the following gradle kotlin dsl build.gradle.kts:

`import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.0.0")
        classpath("com.guardsquare:proguard-gradle:7.0.0")
    }
}

plugins {
    kotlin("jvm") version "1.3.61"
}

group = "mygroup"
version = "1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("junit:junit:4.12")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
    kotlinOptions.freeCompilerArgs += "-Xuse-experimental=kotlin.Experimental"
}

tasks.register<proguard.gradle.ProGuardTask>("proguard") {
    dependsOn("jar")
    configuration("library.pro")
}
`

I copied library.pro from the standalone examples, added the -keepkotlinmetadata line, and replaced the inpath with my jar file from the ./build folder. I run ./gradlew clean build and then ./gradlew proguard in that order.

Is there a way to make library.pro compatible with kotlin? Note that I have a very large number of classes and functions marked with the kotlin "internal" keyword.

**Comment by mrjameshamilton** [comment]
As you're creating a library the Kotlin standard library itself will not be included inside the jar, so that's why ProGuard is telling you about the missing classes.

You can add the compile dependencies as library jars like this:

```
tasks.register<proguard.gradle.ProGuardTask>("proguard") {
    dependsOn("jar")
    libraryjars(sourceSets.main.get().compileClasspath)
    configuration("library.pro")
}
```

**Comment by sithys** [comment]
That did the trick
