### ISSUE TITLE
Obfuscating Guava results in "Stack size becomes negative after instruction"

### ISSUE THREAD

**Issue by Lonzak** [Guardsquare/proguard#86]
Rencently we updated from Guava 27.1 to 28.2 and now get the following error:

> Stack size becomes negative after instruction 

We are using proguard 6.2.2.

```
[proguard] Unexpected error while computing stack sizes:
 [proguard]   Class       = [com/google/common/math/Stats$$Lambda$3]
 [proguard]   Method      = [accept(Ljava/lang/Object;I)V]
 [proguard]   Exception   = [java.lang.IllegalArgumentException] (Stack size becomes negative after instruction [5] invokevirtual #24 in [com/google/common/math/Stats$$Lambda$3.accept(Ljava/lang/Object;I)V])
 [proguard] Error: Stack size becomes negative after instruction [5] invokevirtual #24 in [com/google/common/math/Stats$$Lambda$3.accept(Ljava/lang/Object;I)V]
```

There were previously some related error reports but we are **not** using any android/kotlin. It is standard java...

**Comment by mrjameshamilton** [comment]
Hi @Lonzak , are you still experiencing this issue? If so do you have a reproducible sample that you could share? Have you tried ProGuard 7.0.1?

**Comment by Lonzak** [comment]
It has been a while... I tried to reproduce the issue but I couldn't anymore. So we can close this one.
