### ISSUE TITLE
Gradle Dependency Chain + Maven Local Usage Advice

### ISSUE THREAD

**Issue by sithys** [Guardsquare/proguard#87]
I am developing an interpreter with 4 libraries that depend on each other in a chain:

lib0 depends on kotlin standard library
lib1 depends on ANTLR
lib2 depends on lib0 and lib1 and kotlin standard library
lib3 depends on lib0, lib1, lib2 and kotlin standard library

I am using the MavenLocal task to publish the various gradle packages to my local maven repository on my machine. All the gradle scripts are written in the kotlin gradle dsl.

Is it possible to add to my gradle scripts so that proguard will obfuscate the output, and that the obfuscated jars will be used as input to the next library in the chain? If so, how? Or will all 4 jar files need to be obfuscated at the same time in the final library? Or will the 4 jars need to be obfuscated with a manual command outside of gradle? Any advice would be helpful.

**Comment by mrjameshamilton** [comment]
Hi @sithys,

Thanks for your question! The aim of the issue tracker here is to track technical issues and bugs.

For usage questions like this, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice on your configuration from our team of engineers and skilled community members.
