### ISSUE TITLE
Lib directory gone?

### ISSUE THREAD

**Issue by njardim** [Guardsquare/proguard#88]
Hi,

I've just downloaded ProGuard and when trying to launch the gui via bin\proguardgui.bat where it calls:

java -jar "%PROGUARD_HOME%\lib\proguardgui.jar" %*

It fails to launch the app. 

I can see that the lib directory is gone? Am I missing something is the lib directory really missing or is there a different way to launch the gui?

I'm trying to run Proguard in windows 10.

Thanks in advance.

**Comment by EricLafortune** [comment]
If you've downloaded the prebuilt zip file, the lib directory and its jars are there, and it should just work.

If you've downloaded the source code zip file or if you've cloned the git repository, you'll have to build the jars first: `./gradlew assemble`.

**Comment by njardim** [comment]
You're right. I think that was the problem.
I've downloaded the source code zip file but now I'm downloading the prebuilt zip file from https://github.com/Guardsquare/proguard/releases/tag/v7.0.0 I think this is the one I should be getting. Right?
Thank you.

**Comment by EricSalemi** [comment]
Yes this is the correct link.
