### ISSUE TITLE
ant task no longer included in proguard.jar?

### ISSUE THREAD

**Issue by kortenkamp** [Guardsquare/proguard#97]
I just tried to use the 7.0.1 release instead of 6.x, and our build process fails with ant complaining about an undefined task name. On first inspection it looks like proguard/ant/task.properties is no longer included in proguard.jar. Any reason for that? Or hast something changed that ant is no longer supported?

**Comment by EricLafortune** [comment]
This is a known packaging issue, #52 . We still need to fix it, but you can download the jar from JCenter.

**Comment by kortenkamp** [comment]
thank you for the explanation. Hoping for 7.0.2 then.
