### ISSUE TITLE
how to fix this problem

### ISSUE THREAD

**Issue by xiaoliu10** [Guardsquare/proguard#98]
can't find referenced class java.sql.Timestamp

**Comment by xiaoliu10** [comment]
I use Dontwarn to ignore it, how do I solve it completely?

**Comment by mrjameshamilton** [comment]
Hi @xiaoliu10, it sounds like you might be missing the Java runtime library jar. Please check the troubleshooting section in the manual: https://www.guardsquare.com/en/products/proguard/manual/troubleshooting#unresolvedclass

If the manual does not help, please head over to the [Guardsquare community](https://community.guardsquare.com/?utm_source=github&utm_medium=site-link&utm_campaign=github-community) where you can get tips and advice.
